### ISSUE TITLE
[일본군 위안부 기록] 워딩 수정

### ISSUE THREAD

**Issue by daamable** [seoul-metropolitan-archives/sdaweb#103]
http://52.79.195.15/collections 

<img width="531" alt="스크린샷 2019-03-20 오후 6 04 36" src="https://user-images.githubusercontent.com/39326928/54672111-b8ac5980-4b3a-11e9-8200-63494d64b1cc.png">

<img width="1173" alt="스크린샷 2019-03-20 오후 6 07 31" src="https://user-images.githubusercontent.com/39326928/54672292-1a6cc380-4b3b-11e9-866a-bb0dc7319033.png">

<img width="407" alt="스크린샷 2019-03-20 오후 6 08 17" src="https://user-images.githubusercontent.com/39326928/54672359-2fe1ed80-4b3b-11e9-98cc-a7c3924d5dc1.png">

http://52.79.195.15/collection/comfort-women

<img width="1183" alt="스크린샷 2019-03-20 오후 6 09 35" src="https://user-images.githubusercontent.com/39326928/54672437-5bfd6e80-4b3b-11e9-9e18-5e0847a6c089.png">

<img width="1094" alt="스크린샷 2019-03-20 오후 6 08 52" src="https://user-images.githubusercontent.com/39326928/54672385-40926380-4b3b-11e9-8bcd-261311881e0e.png">

[워딩 수정] 
- 서울대 인권센터 일본군 위안부 기록 -> 서울대 정진성 연구팀이 서울시의 지원을 받아 수집한 ‘위안부’ 기록
- 서울대 인권센터 정진성 연구팀 -> 서울대 정진성 연구팀

[이슈] 

- 시리즈 기술의 정리체계, 보존이력 등에도 해당 워딩이 사용

**Comment by daamable** [comment]
@css3studio 웹페이지의 워딩 수정을 21(목)까지 부탁드립니다. 서울대 연구팀에서 바뀐 명칭이 노출되면 안된다는 요청이 와서 먼저 급하게 요청드립니다.

**Comment by css3studio** [comment]
적용하였습니다

**Comment by daamable** [comment]
감사합니다!
