### ISSUE TITLE
[오시는 길&반갑습니다] 지도 업데이트, 워딩 볼드/선 추가 

### ISSUE THREAD

**Issue by daamable** [seoul-metropolitan-archives/sdaweb#104]
[28일까지. 급하지 않음] 

<img width="530" alt="스크린샷 2019-03-22 오후 5 05 41" src="https://user-images.githubusercontent.com/39326928/54808843-c4c42280-4cc4-11e9-8038-5d21bf6e126a.png">

현재 푸터에 오시는길이 있는데 이게 링크가 제대로 안걸려있고 페이지도 없어서 링크 누르면 메인 화면으로 이동합니다. 
그래서 이 링크를 누르면 팝업 형태로 띄울 수 있게 하면 될 것 같습니다.  
내용은 현재 팝업 형태로 들어간 '반갑습니다'의 아래 부분, 즉 '서울기록원 이용안내' 워딩부터 맨 아래까지의 내용을 그대로 쓰면 될 것 같습니다. 다만 '서울기록원 이용안내' 워딩을 '오시는 길'로만 수정하면 될 것 같습니다. 

<img width="555" alt="스크린샷 2019-03-22 오후 5 07 17" src="https://user-images.githubusercontent.com/39326928/54808906-f63cee00-4cc4-11e9-92b8-bcf7de92b63e.png">

**Comment by css3studio** [comment]
완료하여 적용하였습니다

**Comment by daamable** [comment]
반갑습니다 맨 아래 있는 주소와 문의 부분이 오시는 길에는 빠져있습니다. 용님이 지도 업데이트 해주시면 그 부분 반영과 함께 이 부분도 반영 부탁드립니다.

**Comment by css3studio** [comment]
반영하였씁니다

**Comment by daamable** [comment]
<img width="1152" alt="스크린샷 2019-04-02 오후 8 23 13" src="https://user-images.githubusercontent.com/39326928/55600780-98b2a200-5798-11e9-92a6-9f5d20ba7290.png">

![지도수정4 3](https://user-images.githubusercontent.com/39326928/55600799-b3851680-5798-11e9-9700-0c4bb53efc93.png)
@css3studio
