### ISSUE TITLE
[문의] 워딩 수정 

### ISSUE THREAD

**Issue by daamable** [seoul-metropolitan-archives/sdaweb#105]
<img width="928" alt="스크린샷 2019-03-26 오후 2 41 40" src="https://user-images.githubusercontent.com/39326928/54973935-7325db80-4fd5-11e9-8459-9a90516a92eb.png">

우혜린 주무관 -> 임태원 주무관 02-350-5626

**Comment by mozodev** [comment]
완료

**Comment by daamable** [comment]
<img width="1004" alt="스크린샷 2019-03-27 오전 11 24 36" src="https://user-images.githubusercontent.com/39326928/55045972-416b4e00-5083-11e9-93a1-19ff5300f0cd.png">

추가 요청 사항입니다.

**Comment by mozodev** [comment]
따옴표까지 수정 완료

**Comment by daamable** [comment]
마지막 수정 요청입니다. 
'ㅇㅇ견학 담당 주무관(ㅇㅇㅇ주무관)' -> 'ㅇㅇ견학 담당'(ㅇㅇㅇ주무관)

**Comment by mozodev** [comment]
완료

**Comment by daamable** [comment]
확인하였습니다. 이슈 닫습니다.
