### ISSUE TITLE
[인쇄] 기록 위계 페이지 / 검색 페이지 오류 수정 

### ISSUE THREAD

**Issue by daamable** [seoul-metropolitan-archives/sdaweb#109]
![Image from iOS](https://user-images.githubusercontent.com/39326928/55053961-653d8c80-50a1-11e9-82f0-000f7c2ede38.jpg)

**Comment by daamable** [comment]
[201901250841da89-710c-4c4e-8d87-f7000c1f6886.pdf](https://github.com/seoul-metropolitan-archives/sdaweb/files/3011754/201901250841da89-710c-4c4e-8d87-f7000c1f6886.pdf)

**Comment by mozodev** [comment]
완료

**Comment by daamable** [comment]
검색화면 인쇄 레이아웃 가이드 https://app.moqups.com/ddevc2Sl0I/edit/page/ad2ab1d28

**Comment by daamable** [comment]
위계화면 인쇄 레이아웃 https://app.moqups.com/ddevc2Sl0I/edit/page/aef33dac6
