### ISSUE TITLE
[탐색] 분류내 시리즈 이동

### ISSUE THREAD

**Issue by woonjjang** [seoul-metropolitan-archives/sdaweb#11]
- 분류 내 시리즈 이동 (다중인 경우)

**Comment by daamable** [comment]
- 푸터 검색 눌렀을 때 나오는, 검색어 넣지 않았을 때 나오는 목록 페이지는 없앤다.
- 푸터 검색을 누르면, GNB에서 검색 누를 때 나오는 검색 바가 나온다. 
- GNB에서 이미 검색을 눌렀는데, 또 푸터 검색을 누르면, '움찔' 효과를 준다.

**Comment by daamable** [comment]
검색창에서 ":" 이런 걸 쳤을 때 전체 목록이 나오면 된다.

**Comment by woonjjang** [comment]
검색창 관련 이슈는 https://github.com/seoul-metropolitan-archives/sdaweb/issues/102 로 이동합니다. 
분류내 시리즈 이동은 완료된 이슈여서 닫습니다.
