### ISSUE TITLE
[시리즈 상세페이지_검색도구] 링크 표현 수정 

### ISSUE THREAD

**Issue by daamable** [seoul-metropolitan-archives/sdaweb#112]
- 링크 표현 수정 : URL은 해당 워딩으로 연결하고, 밑줄을 긋고, 색깔을 표현하지 않는다. 

[시리즈] 서울시장실이 운영하는 웹페이지 아카이빙, 2018 
http://52.79.195.15/browse-class/CC-0012/8501
<img width="594" alt="스크린샷 2019-03-28 오전 11 36 22" src="https://user-images.githubusercontent.com/39326928/55125688-d63a7e00-514d-11e9-9193-0475a5a1feb1.png">

[분류_컬렉션] 웹.소셜미디어 컬렉션 
http://52.79.195.15/class/CC-0004
<img width="566" alt="스크린샷 2019-03-28 오전 11 37 53" src="https://user-images.githubusercontent.com/39326928/55125734-f0745c00-514d-11e9-8a96-747aab2b856c.png">

[시리즈] 서울시 공식 소셜미디어 아카이빙 #1, 2017 
http://52.79.195.15/browse-class/CC-0004/8506
<img width="593" alt="스크린샷 2019-03-28 오전 11 39 12" src="https://user-images.githubusercontent.com/39326928/55125783-1e59a080-514e-11e9-81ca-cd97694c9e3e.png">

[시리즈] (컬렉션) 주요 시정사진 컬렉션 이하 25개 시리즈 
http://52.79.195.15/browse-class/CC-0002
<img width="574" alt="스크린샷 2019-03-28 오전 11 42 48" src="https://user-images.githubusercontent.com/39326928/55125910-a049c980-514e-11e9-8397-5da2052b93b8.png">

**Comment by css3studio** [comment]
수정완료
