### ISSUE TITLE
[링크 및 워딩 수정] 

### ISSUE THREAD

**Issue by daamable** [seoul-metropolitan-archives/sdaweb#113]
![스크린샷 2019-04-01 오전 3 01 59](https://user-images.githubusercontent.com/39326928/55293453-b64ad900-5431-11e9-8242-cc1c035ab8d8.png)

소개 > 인사말 
문장 중복에 따른 삭제 
--
왼료

**Comment by daamable** [comment]
![스크린샷 2019-04-01 오전 3 04 04](https://user-images.githubusercontent.com/39326928/55293475-e98d6800-5431-11e9-8dd3-bc5e8672178c.png)
소개 > 서울기록원 홍보 영상
[워딩 수정] 과심 -> 관심 
[링크 수정]  「서울기록원 브랜드 커뮤니티 전략 홍보물 제작 사업」 https://archives.seoul.go.kr/post/18

--
완료

**Comment by daamable** [comment]
![스크린샷 2019-04-01 오전 3 06 30](https://user-images.githubusercontent.com/39326928/55293494-1b9eca00-5432-11e9-907c-065191aad910.png)


소개 > 서울기록원 비전 
[오타 수정] 접근서 -> 접근성 @dragon 

--
완료

**Comment by daamable** [comment]
![스크린샷 2019-04-01 오전 3 08 21](https://user-images.githubusercontent.com/39326928/55293506-3113f400-5432-11e9-8d5b-0d20954e9048.png)

기능 및 조직 구성 > 정책제도관리 
[띄어쓰기] 서울기록관리위원회 구성·운영(우혜린주무관) -> (우혜린v주무관) 

--

완료

**Comment by daamable** [comment]
![스크린샷 2019-04-01 오전 3 11 34](https://user-images.githubusercontent.com/39326928/55293548-910a9a80-5432-11e9-8c9e-216165279b17.png)

추진경과 > 서울기록원 건립 타임랩스 
[띄어쓰기] <건축공사>사진첩 -> <건축공사> 사진첩
--
완료

**Comment by daamable** [comment]
![스크린샷 2019-04-01 오전 3 13 50](https://user-images.githubusercontent.com/39326928/55293565-aa134b80-5432-11e9-8cd1-bb5bfd03d3dc.png)

추진경과 > 서울기록원 건립 본격 추진 
[반점 깨짐에 따른 수정]  (Chrome) 

--
완료

(담) 브리우저마다 깨짐이 발생하는 것 같습니다. 현재 크롬 모바일인데도 깨지네요 ㅠ

**Comment by daamable** [comment]
![스크린샷 2019-04-01 오전 4 02 30](https://user-images.githubusercontent.com/39326928/55293601-1f7f1c00-5433-11e9-965c-11c98d66017a.png)

 - 링크 수정 : ~학술연구용역 완료  https://archives.seoul.go.kr/post/6
 - 시정 사진기록 정리 ~ (서울사진아카이브 구축) 완료 https://archives.seoul.go.kr/post/7
 - 링크 수정 : ‘서울사진아카이브 오픈’ -> ‘서울사진아카이브’에만 링크  
 - 링크 수정 : 정보화전략계획(ISP) 수립 완료 https://archives.seoul.go.kr/post/13
 - 링크 수정 : 서울기록원 슬로건 및 B.I. https://archives.seoul.go.kr/post/14
 - 링크 수정 : 수집전략 개발 용역 https://archives.seoul.go.kr/post/12 
 - 링크 수정 : 시민대상 서비스v프로그램 운영사례 조사 https://archives.seoul.go.kr/post/11
 - 링크 수정 : 서울기록v수집 및 콘텐츠v개발 사업 https://archives.seoul.go.kr/post/15
 - 링크 수정 : 서울기록원 디지털 아카이브 구축 사업 https://archives.seoul.go.kr/post/16
 - 링크 수정 : 주요 시정정보 기록화 사업 완료 https://archives.seoul.go.kr/post/17
 - 링크 수정 : 홍보물 제작 사업 완료 https://archives.seoul.go.kr/post/18

--

완료

(담) 정보화전략계획 링크 오류입니다 ㅠ

**Comment by daamable** [comment]
![스크린샷 2019-04-01 오전 3 39 37](https://user-images.githubusercontent.com/39326928/55293618-51907e00-5433-11e9-81a4-69145d891f6a.png)

이용자 도움말 
실서버(왼쪽) vs 개발서버(오른쪽) 
: 개발서버의 내용/UI 기준으로 실서버에 반영되어야 합니다. 
---
@mozodev 에게 부탁드립니다

**Comment by daamable** [comment]
![스크린샷 2019-04-01 오전 3 41 20](https://user-images.githubusercontent.com/39326928/55293634-7e449580-5433-11e9-8f8d-dbada35b28ee.png)

문의 > 일반문의 
[워딩 수정] <공공기록관리에관한법률> -> <공공기록물 관리에 관한 법률> 

--
완료

**Comment by daamable** [comment]
![스크린샷 2019-04-01 오전 3 42 35](https://user-images.githubusercontent.com/39326928/55293653-a6cc8f80-5433-11e9-8260-668c05df105e.png)

상세검색 
[워딩 수정] 공공기록 -> 시정기록 / 민간기록 -> 시민기록 

--

완료. @mozodev 님 확인 필요합니다

**Comment by daamable** [comment]
![스크린샷 2019-04-01 오전 3 48 08](https://user-images.githubusercontent.com/39326928/55293687-f9a64700-5433-11e9-9882-7ffb698ab02b.png)

조사연구가이드 > 광장 
[링크 수정] 여의도공원 / 광화문광장 : 각각 url을 워딩에 넣고 밑줄로만 표현
대한민국역사박물관 워딩에 http://archive.much.go.kr/data/JD008/folderView.do?jobdirSeq=366 링크 표현

--
@mozodev 수정필요

**Comment by daamable** [comment]
![스크린샷 2019-04-01 오전 3 48 43](https://user-images.githubusercontent.com/39326928/55293706-438f2d00-5434-11e9-8657-7b8f0bc0cc82.png)

조사연구가이드 > 올림픽과 월드컵 
[링크 수정] 해당 url을 각 워딩에 연결하고 밑줄 표시 
1988 하계올림픽 https://www.olympic.org/seoul-1988
'국제스포츠대회' http://theme.archives.go.kr/next/internationalSport/olympicGameA.do
2002 한일월드컵 http://www.fifa.com/worldcup/archive/koreajapan2002/index.html
'다시보는 2002 FIFA 월드컵' http://theme.archives.go.kr/next/worldCup2009/viewMain.do
'2002한일월드컵' http://www.archives.go.kr/next/search/stSubjectDescription.do?id=003123&pageFlag=
'월드컵조직위원회' http://www.archives.go.kr/next/search/listSubjectDescription.do?id=005782&pageFlag=

--
@mozodev 님 수정필요

**Comment by daamable** [comment]
![스크린샷 2019-04-01 오전 3 48 54](https://user-images.githubusercontent.com/39326928/55293723-8d781300-5434-11e9-90d2-0b63a169c31b.png)

조사연구가이드 > 공원 [링크 수정] 해당 url을 워딩에 연결하고 밑줄 표시 
웹보기 http://lib.seoul.go.kr/search/detail/CATCRZ000000057131?mainLink=/searchS/eaz&briefLink=/searchS/eaz/result?folder_id=null_A_q=서울도시계획_A_st=KWRD_A_si=TOTAL
원래 url 있던 영역의 반점은 지우기 

--

@mozodev 님 수정필요

**Comment by daamable** [comment]
![스크린샷 2019-04-01 오전 4 14 56](https://user-images.githubusercontent.com/39326928/55293750-c0220b80-5434-11e9-94d5-bfada987c9ce.png)

서울사진아카이브 [링크 연결] 
'이용자 커뮤니티에서 질문하기' 버튼에 다음의 링크 연결 https://archives.seoul.go.kr/community 

--
완료

**Comment by daamable** [comment]
![스크린샷 2019-04-01 오전 4 16 17](https://user-images.githubusercontent.com/39326928/55293768-f1024080-5434-11e9-826b-e97acd662b5a.png)

일본군 위안부 기록 [링크 연결] 
'기록 탐색' 버튼에 다음 링크 연결 https://archives.seoul.go.kr/class/CC-0003

--
완료

**Comment by css3studio** [comment]
> ![스크린샷 2019-04-01 오전 3 01 59](https://user-images.githubusercontent.com/39326928/55293453-b64ad900-5431-11e9-8242-cc1c035ab8d8.png)
> 
> 소개 > 인사말
> 문장 중복에 따른 삭제

완료

**Comment by mozodev** [comment]
완료

**Comment by daamable** [comment]
조사연구가이드 > 조사연구가이드란? 링크 수정 http://archives.seoul.go.kr/user-guide/3
