### ISSUE TITLE
[일본군'위안부'컬렉션] 그룹/아이템 개수 표현 수정 

### ISSUE THREAD

**Issue by daamable** [seoul-metropolitan-archives/sdaweb#114]
![스크린샷 2019-04-03 오후 12 01 56](https://user-images.githubusercontent.com/39326928/55455540-fd49f180-561e-11e9-8015-a112c6d51be1.png)

현재 해당 컬렉션의 3개 시리즈가 사진+제목으로 보이고, 제목 옆 괄호 안에 숫자가 표시됨
이 숫자는 시리즈 하위 파일+아이템의 개수를 합친 것. 파일과 아이템 개수를 합쳐서 보여주는 것은 이용자가 시리즈의 정보를 파악하는데 도움이 안되는 정보.
- 아이템 기준으로 정보를 맞춘다. 
 : [워딩 수정] 그룹/아이템 -> 시리즈 
 : [숫자 수정] (해당 시리즈의 총 아이템 개수) 
  현재 기준 
  일본군 '위안부' 관계 영상기록(2)
  일본군 '위안부' 관계 사진기록(32) 
  일본군 '위안부' 관계 문서기록(n개) (일일이 세긴 너무 많네요 ㅠ 134개보다 적겠지요)

**Comment by mozodev** [comment]
완료
