### ISSUE TITLE
[포스트 관리] 모바일 대응(운영)

### ISSUE THREAD

**Issue by daamable** [seoul-metropolitan-archives/sdaweb#121]
포스트 관리 영역에서 작성 가능한 뉴스, 칼럼, 연구보고서의 경우 

1. 모바일에서 본문 post의 글씨 크기가 작다. 
  현재 모바일 폰트 사이즈 설정 
    font-size: 1rem;
    line-height: 1.8rem;
    margin-bottom: 1.25rem;

2. 모바일에서 사진이 원래 비율을 유지하지 않고, height는 유지되고 width만 조정되어서 아래위로 길게 표현된다. 
https://archives.seoul.go.kr/post/64

**Comment by css3studio** [comment]
1번 수정하여 개발서버에 적용하였습니다

**Comment by css3studio** [comment]
2번 문제는 개발단에서 이미지의 높이값을 지정해 줘서 발생한 문제입니다. 특별한 이유가 없다면 개발단에서 해당 코드를 삭제하면 좋겠습니다. 다만, 현재 상태에서도 이미지 비율이 유지 되도록 css 를 보상하여 개발서버에 적용하였습니다
