### ISSUE TITLE
(4일) [회원]회원탈퇴

### ISSUE THREAD

**Issue by seoularchives** [seoul-metropolitan-archives/sdaweb#13]

**Comment by seoularchives** [comment]
[개인]에게 회원약관에서 관리자에게 요청하면 해당되는 개인에게 반영한다.

**Comment by daamable** [comment]
[이용약관에 해당 정책 요청] 
회원이 계정을 탈퇴할 경우, 
- 1) 개인정보, 로그, IP를 탈퇴 시점에 맞추어 DB에서 삭제한다.
- 2) 개인정보, 로그, IP를 n년간 유지 후 DB에 삭제한다. / n년까지는 사용자 접근만 안될 뿐, DB에 남겨놓는다. 탈퇴한 개인이 해당 계정의 복원을 요청시 복원해줄 수 있다. ('차단'의 개념) 
- or anything else? 
- 기술적으로도 4일 정도 시간 필요

**Comment by daamable** [comment]
- 탈퇴 회원의 개인정보, 로그, IP는 통계 파악 직전까지 유지하고, 통계 파악 직후 삭제한다. (통계의 주기는 대략 1달) 
- IP는 바로 삭제되어도 상관 없다.  
- 탈퇴 시 안내 문구가 출력된다. 
 (슬로워크 제안 - 임태원 주임님 컨펌)

**Comment by daamable** [comment]
https://app.moqups.com/ddevc2Sl0I/edit/page/a8f5601a2

**Comment by mozodev** [comment]
완료
