### ISSUE TITLE
[검색]상위 집합체 정보 노출

### ISSUE THREAD

**Issue by seoularchives** [seoul-metropolitan-archives/sdaweb#18]

**Comment by daamable** [comment]
<img width="695" alt="스크린샷 2019-03-17 오후 6 12 27" src="https://user-images.githubusercontent.com/39326928/54488045-50fad200-48e0-11e9-97e1-9d14547ac163.png">

[정책 협의 요청] 

검색 결과에서 도출한 목록의 개별 단위에 메타데이터를 얼마나 노출할 것인가

1) 분류
- <서울시의회 관련 사진기록> 시리즈의 메타값 표현이 best. 즉, 
 - 메타데이터 1번 라인에는 주제, 출처, 컬렉션 등 값만 표현된다. (만일 주제가 없을 경우 '없음'으로 표시할지, 표현하지 않을지는 판단 필요)

2) 계층 
- 파일, 아이템 단위의 경우 상위 계층(파일은 시리즈, 아이템은 파일)이 들어가는 것이 좋은 것인지 

3) 생산자 
4) 온라인 열람 가능 표시 

메타데이터값이 4줄이 되는데 이들이 다 들어가는 것을 요청하는 것인지에 대한 판단 필요 
줄이 길어질 경우 보다 효율적으로 어떻게 표현할 것인지는 더 고민해야 할 것

**Comment by daamable** [comment]
[답변] 
2. 안 나와도 된다. (현재 상위에서 보여주고 있기 때문에)
4. 온라인 열람 표시 

총 3줄 

- 온라인 열람 가능한 것들은 원문/컴포넌트가 있어야 한다. 

[다음 사업] 
이후 온라인 열람 의 워딩 수정, 이미지 등 표현 방식 고민
