### ISSUE TITLE
컴포넌트 파일 확인

### ISSUE THREAD

**Issue by mozodev** [seoul-metropolitan-archives/sdaweb#25]
사진아카이브 파일 예전 업로드한 것과 
현재 서버 업로드된 파일
용량 비교 필요.

**Comment by woonjjang** [comment]
[주말] 운짱이 작업 진행

**Comment by woonjjang** [comment]
1차 업로드 확인 완료

**Comment by woonjjang** [comment]
사진아카이브 및 관련 자료 확인 완료.

**Comment by daamable** [comment]
[내용 확인] 
- 실서버에 업로드한 전체 사진 파일 중 일부가 누락되어, 이를 확인하여 모두 업로드
