### ISSUE TITLE
[열람] 개인정보 인증 (디자인, 기술, 정책 이슈) 

### ISSUE THREAD

**Issue by woonjjang** [seoul-metropolitan-archives/sdaweb#26]
- 정책 확인
- 페이지 시나리오

1) 기본 목록에서 타 목록으로 옮기는 쉬운 방법 필요. 
https://app.moqups.com/ddevc2Sl0I/edit/page/a3e09b217

2) 개인정보 인증
https://app.moqups.com/ddevc2Sl0I/edit/page/ae5bf7874

3) 보관함에서 신청

https://app.moqups.com/ddevc2Sl0I/edit/page/a14b03f1a

**Comment by woonjjang** [comment]
개인정보 인증은 최대한 별도창이 아닌 내부 폼과 api 연결방식으로 유도

**Comment by daamable** [comment]
목업 페이지 디자인 @kimyonghyun123

**Comment by daamable** [comment]
윤현숙 주임님과 moqup 확인

**Comment by daamable** [comment]
- 현재 페이지 디자인, 기능 개발 필요한 상황
- 오픈 이후, 임태원 주무관님, 윤현숙 주무관님 동석 하에 최종 컨펌 한다.

**Comment by daamable** [comment]
- moqup https://app.moqups.com/ddevc2Sl0I/edit/page/ae5bf7874
- 현재 휴대폰 통한 개인정보 인증 이외에 지난번 제안 드린 추가 안(휴대폰 없을 경우 개인정보 인증)에 대한 결정의 확인 필요 
 - (1안) 휴대폰만으로 개인정보 인증을 진행한다. 
 - (2안) 휴대폰 이외에도 개인정보를 확인하여 진행한다. 이 경우 관련 문서/절차는 00가 있다. 
 - (3안) 기타  
- 정책 확인될 경우, 목업에 따른 페이지 디자인, 화면 개발이 이루어질 예정

**Comment by daamable** [comment]
1안으로 진행한다. 
이 경우 개인정보 인증 서비스 연결이 필요하다.

**Comment by daamable** [comment]
https://www.kmcert.com/cert/serviceReq.jsp

**Comment by daamable** [comment]
개인정보인증 api를 연결한다. 
개인정보인증 버튼 옆에 다음 워딩을 추가한다. 
"개인정보인증은 서울기록원의 기록정보 서비스 활용을 위한 과정이며, 최초 1회 인증 이후 다시 인증하지 않아도 됩니다."
- moqup https://app.moqups.com/ddevc2Sl0I/edit/page/a239df910
