### ISSUE TITLE
[요청 목록] 정보오류신고 목록, 문의 (일반, 견학, 기록열람) 

### ISSUE THREAD

**Issue by woonjjang** [seoul-metropolitan-archives/sdaweb#27]

**Comment by daamable** [comment]
[현재 상황] 
inquiry : 필드를 넣어서 요청. 기록 아이템과는 상관 없음 (일반 문의, 견학 요청)
request : 1개 기록 아이템이라도 relation 걸어서 의견 제시 (방문열람. 정보오류신고)

[확인] 
- 견학(inquiry) :  운영관련, 건축관련 - 일반문의 - 견학관련 - 열람 신청 관련
- 방문 열람 : 보관함 (목업 확인 - 윤현숙 주인님 확인)

**Comment by woonjjang** [comment]
<img width="593" alt="스크린샷 2019-03-17 오후 6 37 39" src="https://user-images.githubusercontent.com/6022883/54488326-daf86a00-48e3-11e9-9efb-ffea80f7663c.png">
28일 시점(태원님이 요청한 적이 있음)
- 운영관련, 건축관련
- 일반문의
- 견학관련
- 열람 신청 관련

**Comment by daamable** [comment]
- 견학의 유형 3가지 : 기관견학, 전시견학, 보존시설견학

**Comment by daamable** [comment]
: 문의 >  
  - 운영관련, 건축관련 (추가 예정? 문의 페이지에 관련 내용 워딩 추가?) 
  - 일반문의 (현재 적용) 
  - 견학 (기관, 전시, 보존시설) 
  - 기록 열람 신청     

  — 해당 기능 최종 오픈 여부 및 시기 확인  

 : 관리 > 요청목록 
 - 오류신고 목록 
 - 일반문의 목록 
 - 견학신청 목록 
 - 요청 목록 
  - 일반, 방문, 보존여부 확인, 반출, 복사(뒤 3개 삭제 예정)  

 — 운영관련, 건축관련 추가 예상
 — 견학신청 나뉘어야 할 것으로 보임 

 : 내 계정 > 보관함 

 - 기본목록
 - 방문열람신청
 - 보존여부확인
 - 반출 
 - 복사  

 — 뒤 3개 삭제 예정 
 — moqup https://app.moqups.com/ddevc2Sl0I/edit/page/a14b03f1a
 — 이름(실명인증), 이메일, 연락처, 사용목적 이외 추가 필드? 
 — 보관함에서 기본 목록 -> 방문열람 이동 시 드래그로 이동 외 UI 적용? (체크박스로 선택 후 이동 등) 
보관함에서 기록 이동 UI 
 —  현재 파일, 아이템 둘 다 신청 가능한데, 정책적으로 파일까지 신청?

**Comment by daamable** [comment]
보관함에 문구를 넣는다. 
"열람 신청은 파일과 아이템 단위 모두 신청이 가능하나, 현장에서 기록을 제공할 때는 파일 단위로 제공됩니다"

**Comment by daamable** [comment]
(1) 문의 

 - 현재 일반문의 신청 칸 외에 견학 신청 문의, 기록 열람 신청 문의 칸을 추가한다. 
 - 견학 신청 문의 업무는 실제 5월에 오픈하므로, 이는 구현하되 가려놓는다.  

 **: 기록 열람 신청 문의 화면을 구현한다.** 

 (2) 기록 열람 후 보관함 추가 

  - 현재 기록을 열람하면서 파일, 아이템 세부페이지에서 열람하고 싶은 기록을 보관함을 추가할 수 있다. 
  - 파일 단위로 제공하는 것을 기본으로 한다. (정책) 
 
  (3) 보관함에 추가된 기록의 기록 열람 신청 

 - [보관함] 탭에 담긴 기록 중 방문열람 신청할 기록들을 [방문열람] 탭으로 이동한다.  
 
 **: (moqup) 보관함 목록 앞 체크박스와 이동 버튼을 구현한다.  
    : 현재 보관함 화면에서 보존여부확인, 반출, 복사 탭을 삭제한다.
    : 열람신청 시 개인정보를 확인하는 ‘개인정보 인증’ 기능을 추가한다. 이에 대해선 (4) 참고**
 
 - [방문열람] 탭으로 이동한 기록을 방문열람 신청한다. 
  - 이름, 이메일, 연락처, 사용목적을 입력하고 [방문열람 요청하기] 버튼을 누른다.  

 : (열람 신청은 파일 단위를 기본으로 한다. 그래서 실제 아이템을 열람 신청하더라도 파일 단위로 제공한다)      
보관함 신청 페이지의 신청 버튼 옆에 다음의 문구를 넣는다. 
  **"열람 신청은 파일과 아이템 단위 모두 신청이 가능하나, 현장에서 기록을 제공할 때는 파일 단위로 제공됩니다"**  
 

 (4) 개인정보 인증 신청  

   - 개인정보 인증 시 핸드폰을 기준으로 구현한다. 
  : [개인정보 인증 서비스]를 신청(비용은 우선 슬로워크에서 부담), 테스트하고 적용한다.   
  : (moqup) 개인정보 인증 화면  

 (5) 관리 > 요청 목록  

 - 현재 요청 목록의 ‘오류신고 목록’, ‘일반문의 목록’ 외에 ‘견학신청 목록’, ‘요청 목록’이 수정 대상
 - 견학신청 기능은 외부로 5월까지 노출하지 않으나, 관리 상 기능은 구현된다.  
 **: [견학신청 목록] 메뉴에는 세부 게시판으로 [일반], [전시], [보존 시설 견학]을 구분한다.**    
 - 현재 ‘요청목록’ 게시판은 ‘열람신청 목록’ 게시판으로 사용한다.
 **: [요청목록] 게시판 이름을 [열람신청 목록] 게시판으로 수정한다.** 
 : 이 게시판에는 이용자들이 보관함을 통해 열람 신청을 요청한 목록들이 업로드된다. 

 - 각 게시판별로 번호를 부여한다. 
 - 각 게시판의 각 필드에 체크박스를 부여하여 선택할 수 있게 한다. 
 - 엑셀 다운로드 기능을 붙인다. (게시판 외부와 내부 필드를 포함하여 다운로드가 가능하다) 
 - 각 게시판의 세부 페이지를 접속하기 위해 번호가 아닌 필드 전체에 링크가 붙어있다. 
 - 기록의 개수

**Comment by daamable** [comment]
문의 요청 시 메일이 간다.

**Comment by daamable** [comment]
https://app.moqups.com/ddevc2Sl0I/edit/page/adb870603

**Comment by daamable** [comment]
목업 수정 https://app.moqups.com/ddevc2Sl0I/edit/page/a476bf27d

**Comment by mozodev** [comment]
완료

**Comment by daamable** [comment]
관리 > 문의 내에서 일반, 견학, 기록열람 구분

**Comment by daamable** [comment]
개인정보인증 설명 워딩 : 최초 1회, 그 다음부터는 가능

**Comment by mozodev** [comment]
견학신청을 클릭하면 '소속', '인원' 필드 추가

**Comment by mozodev** [comment]
상태 변경 후 리프레시

**Comment by daamable** [comment]
기록열람신청 목록 목업 업데이트 
https://app.moqups.com/ddevc2Sl0I/edit/page/a808d907c
