### ISSUE TITLE
[Main] [회원] 비밀번호 찾기

### ISSUE THREAD

**Issue by woonjjang** [seoul-metropolitan-archives/sdaweb#3]

**Comment by daamable** [comment]
<img width="885" alt="스크린샷 2019-03-21 오전 2 54 13" src="https://user-images.githubusercontent.com/39326928/54707558-b8d14700-4b84-11e9-9644-102c5a4ea6a4.png">

- 다른 건 잘되는데(회원가입 후 로그인 후 메인화면 로드) 비밀번호 재설정 부분에서 '이메일 입력'을 요구하면서 비밀번호 입력 칸이 나오는 상황입니다.

**Comment by daamable** [comment]
- 비밀번호 재설정 기능 가능 
 : 비밀번호 재설정 이후 '비밀번호가 재설정되었습니다' 정도의 메세지가 떠서, 이용자는 비밀번호의 변경 상황을 확인할 수 있다.

**Comment by daamable** [comment]
- 로그인 화면에서 비밀번호를 잃어버려서, 비밀번호 초기화 버튼 누르고 비밀번호 재설정 화면에 들어가서 재설정 링크 발송을 위한 이메일을 작성하면 403 에러가 뜬다.

**Comment by daamable** [comment]
실서버 배포 시 이메일 계정 archive.seoul.go.kr 으로 변경

**Comment by daamable** [comment]
443 포트 오픈 후 이메일 계정 확인

**Comment by daamable** [comment]
재전송 이메일 전송 시 링크(O) - 버튼(X) 다른 문제

**Comment by daamable** [comment]
비밀번호 입력 시 규칙 어긋나면 바로 알려주는 기능 validation

**Comment by daamable** [comment]
![비번찾기 텍스트 컬러와 링크](https://user-images.githubusercontent.com/39326928/55293800-46d6e880-5435-11e9-924f-59db50b2ae0d.jpg)

가입되어있는 이메일 주소입니다. 비밀번호를 잊으셨나요? 
- 텍스트 강조 : 밑줄, 컬러(블루)

**Comment by woonjjang** [comment]
4월 2일 해결완료
