### ISSUE TITLE
연구보고서 내용 확인  / 썸네일 확인

### ISSUE THREAD

**Issue by woonjjang** [seoul-metropolitan-archives/sdaweb#32]

**Comment by woonjjang** [comment]
- 텍스트와 연구보고서 내용 에디터 수정(?)

**Comment by daamable** [comment]
<img width="311" alt="스크린샷 2019-03-12 오후 1 41 56" src="https://user-images.githubusercontent.com/39326928/54175045-9d9f7100-44cc-11e9-8812-ab5e098368a1.png">

크롬에서 체크(브라우저마다 다른지) / 박스보다 이미지 좀 작은 형태로 /
