### ISSUE TITLE
소개 내용 확인  / 썸네일 확인

### ISSUE THREAD

**Issue by woonjjang** [seoul-metropolitan-archives/sdaweb#33]

**Comment by daamable** [comment]
글씨 작게 수정

**Comment by daamable** [comment]
서울기록원 홍보 영상
전략에 대해 관시이 있으신 분은 -> 전략에 대해 관심이 있으신 분은

**Comment by daamable** [comment]
<img width="304" alt="스크린샷 2019-03-12 오후 1 39 01" src="https://user-images.githubusercontent.com/39326928/54174933-35e92600-44cc-11e9-8db6-c3be0f274349.png">

흰 줄 없애기 / 이미지랑 버튼 사이즈 맞추기 (글자에 맞춰서 이미지 키우기)
