### ISSUE TITLE
소개 : 브레드크럼 수정 

### ISSUE THREAD

**Issue by daamable** [seoul-metropolitan-archives/sdaweb#44]
Home > 소개 

Home > 서울기록원 > 소개 

로 수정 
<img width="249" alt="2019-03-08 10 33 32" src="https://user-images.githubusercontent.com/39326928/54001193-c43c6f80-418d-11e9-8004-d437669fc3e4.png">

**Comment by woonjjang** [comment]
뉴스, 연구보고서
Home > 서울기록원 >  뉴스
Home > 서울기록원 >  연구보소서

소개쪽 타 메뉴는 브레드크럼 변경 완료.
