### ISSUE TITLE
[Sub] [반갑습니다] 서울기록원 지도 수정(design)

### ISSUE THREAD

**Issue by daamable** [seoul-metropolitan-archives/sdaweb#45]
네이버지도 캡쳐 
혁신센터 내로 보이도록

**Comment by kimyonghyun123** [comment]
![지도](https://user-images.githubusercontent.com/48339928/54132537-bde11880-4457-11e9-8fd6-cf9f64da3fd3.jpg)

**Comment by woonjjang** [comment]
- 지도를 이용자들이 보고, 서울기록원에 어떻게 갈 수 있는지 와 닿지가 았는다. 
- 50플러스 서부 캠퍼스 입구 -> 서울기록원 입구로 변경한다. (정문) / 불광역 2번출구 표시를 바꾼다.

**Comment by woonjjang** [comment]
* 다른 곳에서 진행하는 레퍼런스를 올려주거나 조사해 달라.

**Comment by daamable** [comment]
서울기록원 주소 추가 : 오시는 길 밑으로(브로셔 이미지랑 주요하게)

**Comment by seoularchives** [comment]
명확하게 공유동과 50플러스 서부센터가 명시되면 좋겠다.

**Comment by woonjjang** [comment]
지도 재 수정 부탁드립니다. (위에 코멘트 확인하세요.)

**Comment by kimyonghyun123** [comment]
![지도수정](https://user-images.githubusercontent.com/48339928/54336537-aa0fff00-466f-11e9-9464-333341ef766c.jpg)

**Comment by mozodev** [comment]
반영 완료

**Comment by kimyonghyun123** [comment]
![지도](https://user-images.githubusercontent.com/48339928/54340398-a2098c80-467a-11e9-9162-f8c254b53471.jpg)

**Comment by daamable** [comment]
[지도 디자인 수정] 
- 주요 대로와 지하철(불광역) 등 주요 기관들만 명확히 표현 
- "차량 이동 시" : 빨간색(아래서 위로) / "도보 이동 시" : 파랑색 등 워딩 표현 
- 약도 느낌 http://www.hira.or.kr/dummy.do?pgmid=HIRAA040095000000

**Comment by daamable** [comment]
[워딩 수정] 
- 추석, 설날 -> 추석, 설날 당일 
- 지하철 : 볼드 넣기 

이 부분 워딩은 @woonjjang 이 수정했는데 @css3studio 님 스타일 한번만 확인 부탁드립니다.

**Comment by daamable** [comment]
지하철 도 볼드 넣기

**Comment by css3studio** [comment]
http://52.79.195.15/#

**Comment by daamable** [comment]
워딩은 해결 되었고, 용님이 지도 올려주시면 반영 부탁드립니다.

**Comment by kimyonghyun123** [comment]
![지도](https://user-images.githubusercontent.com/48339928/54575982-b7473800-4a39-11e9-8768-0f8f77c5a448.jpg)
3x으로  전달드립니다.


[담의 댓글] 20일까지 이 지도를 반영 부탁드립니다. 이후 28일까지 지도 변경 요청을 반영하여, 변경된 지도를 다시 업로드할 예정입니다.

**Comment by daamable** [comment]
[28일 이슈] 
- 청년허브, 서울시사회적경제지원센터 건물을 지운다. 
- 미래청, 공유동 크기를 키운다. 
- 도보이용 시 도로, 즉 서울혁신파크 입구 위치를 위로 옮긴다. 
- 서울기록원 입구 위치를 위로 옮긴다. 
- 서울기록원과 50+ 건물 위치를 바꾼다. 
- 서울기록원 건물은 50+ 건물을 감싸고 있는 형태이다. (이 부분 제가 전화 설명)
- 서울혁신파크 입구로 들어오면 우체국 건물이 있다.

**Comment by daamable** [comment]
![KakaoTalk_Photo_2019-03-19-21-22-21](https://user-images.githubusercontent.com/39326928/54605672-24d08400-4a8d-11e9-9b85-16f017b66f50.jpeg)


[임태원 주무관님이 직접 그려주신 지도]

**Comment by kimyonghyun123** [comment]
![지도수정](https://user-images.githubusercontent.com/48339928/54656383-bc26ed00-4b08-11e9-89dc-f74d330b2899.jpg)

**Comment by css3studio** [comment]
적용하였는데, 화질이 좀 떨어져 보이네요. 
문제 삼을수도 있겠습니다

**Comment by kimyonghyun123** [comment]
![지도수정](https://user-images.githubusercontent.com/48339928/54735017-e058fb80-4be6-11e9-8fcf-b57b8f10c33c.png)

**Comment by kimyonghyun123** [comment]
수정요청 반영해서 다시 업로드하겠습니다. 해상도를 3배더 높였습니다.

**Comment by kimyonghyun123** [comment]
![Group 2@3x](https://user-images.githubusercontent.com/48339928/54736978-14391e80-4bf1-11e9-8152-fb0eaafa0fd1.png)

**Comment by kimyonghyun123** [comment]
우체국 -> 논번우편집중국으로 수정완료했습니다.

**Comment by daamable** [comment]
녹번우편집중국 -> 녹번동 우편취급국 / 도보이용시 -> 도보이동시 / 불광역 2번출구 와 도보이용시 파란 라인이 겹침

**Comment by kimyonghyun123** [comment]
![지도3 25](https://user-images.githubusercontent.com/48339928/54892309-6f6e5800-4ef4-11e9-8a2d-320a7abdb7df.png)
