### ISSUE TITLE
[design] 인사말 라인 수정 

### ISSUE THREAD

**Issue by daamable** [seoul-metropolitan-archives/sdaweb#46]
<img width="1170" alt="2019-03-08 10 37 23" src="https://user-images.githubusercontent.com/39326928/54001310-33b25f00-418e-11e9-82c1-d6bc1d7df75e.png">

라인 오른쪽으로 맞춤

**Comment by woonjjang** [comment]
100%로 맞춘 상황

**Comment by woonjjang** [comment]
http://52.79.195.15/about
