### ISSUE TITLE
전체적 링크 색깔 표현(용)

### ISSUE THREAD

**Issue by daamable** [seoul-metropolitan-archives/sdaweb#48]

**Comment by woonjjang** [comment]
옅은 파란색

**Comment by kimyonghyun123** [comment]
전체범위
color =#019dcb, underline 추가

**Comment by css3studio** [comment]
완료

**Comment by css3studio** [comment]
http://52.79.195.15/about
http://52.79.195.15/about/progress
http://52.79.195.15/post/135
http://52.79.195.15/user-guide/28
http://52.79.195.15/about/inquiry
http://52.79.195.15/research-guide/30
