### ISSUE TITLE
라인 맞추기 : 자세히보기 전으로 / 자세히보기 단어 없이 버튼만 있는 스타일로 변경(용)

### ISSUE THREAD

**Issue by daamable** [seoul-metropolitan-archives/sdaweb#49]
<img width="927" alt="2019-03-08 10 41 21" src="https://user-images.githubusercontent.com/39326928/54001482-d36fed00-418e-11e9-8be5-c24d2087be37.png">

**Comment by kimyonghyun123** [comment]
![앵커버튼있는대로 수정](https://user-images.githubusercontent.com/48339928/54114083-f3bcd780-442c-11e9-98d4-c7b400913f89.jpg)

**Comment by css3studio** [comment]
스테프 인원이 많아서 높이가 길어지는 경우의 디자인 고려 필요

**Comment by css3studio** [comment]
http://52.79.195.15/about/organization
