### ISSUE TITLE
이용자도움말 내 디자인 수정 / 버튼 (용)

### ISSUE THREAD

**Issue by daamable** [seoul-metropolitan-archives/sdaweb#53]
<img width="1037" alt="2019-03-08 10 52 27" src="https://user-images.githubusercontent.com/39326928/54001936-53e31d80-4190-11e9-8a93-23693fdb1453.png">
<img width="1058" alt="2019-03-08 10 52 33" src="https://user-images.githubusercontent.com/39326928/54001937-55144a80-4190-11e9-80e5-bf03fc38ef4e.png">

파란색 컨셉 제거 -> 회색 컨셉으로

**Comment by daamable** [comment]
버튼 수정

**Comment by kimyonghyun123** [comment]
![이용자도움말 상세](https://user-images.githubusercontent.com/48339928/54110887-e6501f00-4425-11e9-8335-1ddb3c54abb8.jpg)

**Comment by kimyonghyun123** [comment]
이미지 첨부 완료

**Comment by css3studio** [comment]
http://52.79.195.15/user-guide/28
