### ISSUE TITLE
[이용자 커뮤니티] 워딩 수정 / 기능 수정 

### ISSUE THREAD

**Issue by daamable** [seoul-metropolitan-archives/sdaweb#54]
<img width="942" alt="2019-03-08 10 56 07" src="https://user-images.githubusercontent.com/39326928/54002103-ceac3880-4190-11e9-80dd-87a62590fd06.png">

문구 수정 및 탭별 문구 추가

**Comment by daamable** [comment]
<img width="277" alt="스크린샷 2019-03-12 오후 1 46 57" src="https://user-images.githubusercontent.com/39326928/54175222-5b2a6400-44cd-11e9-973e-e362155d50f0.png">


시간 분 초 없애기

**Comment by daamable** [comment]
IE 에서 깨져보이는 현상

**Comment by daamable** [comment]
Thread

**Comment by daamable** [comment]
글 안에서 다시 버튼명 글쓰기 버튼 말고 '댓글 달기'

**Comment by daamable** [comment]
<img width="187" alt="스크린샷 2019-03-12 오후 1 54 23" src="https://user-images.githubusercontent.com/39326928/54175465-5ade9880-44ce-11e9-8432-2bd28f156dd7.png">


링크 통일

**Comment by daamable** [comment]
<img width="288" alt="스크린샷 2019-03-12 오후 1 54 49" src="https://user-images.githubusercontent.com/39326928/54175479-69c54b00-44ce-11e9-8f8b-ab1a3c4b55ab.png">


초 빼기

**Comment by woonjjang** [comment]
이용자 커뮤니티 작성된 글에 글쓰기를 하면 글이 아래로 붙어서 작성되어야 하는 부분 지적
글쓰기 -> 댓글로(세부에서 밑에 글 쓰는 경우)

**Comment by daamable** [comment]
> <img alt="2019-03-08 10 56 07" width="942" src="https://user-images.githubusercontent.com/39326928/54002103-ceac3880-4190-11e9-80dd-87a62590fd06.png">
> 
> 문구 수정 및 탭별 문구 추가

- 일반문의 앞에 '[i]' 지우기
- 일반문의 워딩은 링크이므로 링크 표현하기 (밑줄)

**Comment by daamable** [comment]
링크 표현은 링크가 걸린 해당 워딩에 밑줄만 넣는 것으로 통일합니다. (볼드, 색깔 X)

**Comment by daamable** [comment]
- 질문 포스팅에 댓글을 쓰면, Thread 형태로 나온다(디자인, 기술 이슈 포함)
- 28일 이슈로 넘긴다.
