### ISSUE TITLE
[탐색] 분류 부분의 UI 표시 방법의 변경

### ISSUE THREAD

**Issue by woonjjang** [seoul-metropolitan-archives/sdaweb#6]
1. 군 -> 분류라고 표현한다. 
2. 목록으로 뿌려주고 있는 항목을 분류라고 표시하고, 아이콘을 삭제한다. 위에서 아래로 노출되는 게 아니라 옆에 나오도록 한다.

**Comment by woonjjang** [comment]
(Class) 말고, 어떤 Class 값인지 확인 가능하게

**Comment by woonjjang** [comment]
<img width="1318" alt="스크린샷 2019-03-14 오전 12 30 24" src="https://user-images.githubusercontent.com/6022883/54291983-c15bd780-45f0-11e9-9598-c366dcfe1da1.png">

컨펌 및 의견 부탁드립니다.

**Comment by daamable** [comment]
<img width="377" alt="스크린샷 2019-03-15 오후 2 24 19" src="https://user-images.githubusercontent.com/39326928/54410277-0f2a2a00-472e-11e9-81a7-c613c6a279f8.png">


(Collection)분류 : 둘 사이 띄어쓰기 필요한 듯 보입니다.

**Comment by daamable** [comment]
> <img alt="스크린샷 2019-03-14 오전 12 30 24" width="1318" src="https://user-images.githubusercontent.com/6022883/54291983-c15bd780-45f0-11e9-9598-c366dcfe1da1.png">
> 
> 컨펌 및 의견 부탁드립니다.

제 의견은 탐색 최초 분류가 주제, 출처Provenance, 컬렉션으로 바뀌어서 
저 위 파란색 동그라미 Organization도 Provenance로 바뀌는 게 맞지 않을까 싶습니다. 
이 부분 확인하겠습니다.
