### ISSUE TITLE
탐색 페이지 

### ISSUE THREAD

**Issue by daamable** [seoul-metropolitan-archives/sdaweb#60]
<img width="1190" alt="2019-03-08 11 19 51" src="https://user-images.githubusercontent.com/39326928/54003172-973f8b00-4194-11e9-9b27-89efdd543cfe.png">

문구 반영 

&

**Comment by seoularchives** [comment]
문구 추가 및 스타일 변경

**Comment by daamable** [comment]
<img width="998" alt="스크린샷 2019-03-12 오후 2 43 32" src="https://user-images.githubusercontent.com/39326928/54177343-418d1a80-44d5-11e9-8eaf-85253d3b0705.png">



기타 버튼 맨 아래로

**Comment by daamable** [comment]
<img width="999" alt="스크린샷 2019-03-12 오후 2 53 40" src="https://user-images.githubusercontent.com/39326928/54177739-a5fca980-44d6-11e9-9f2e-c0810d1d3193.png">


디자인 요청 : 박스 중간 사이 공간 주기 / 테두리 빼기 
http://discovery.nationalarchives.gov.uk/browse 
<img width="572" alt="스크린샷 2019-03-12 오후 2 55 00" src="https://user-images.githubusercontent.com/39326928/54177788-d2182a80-44d6-11e9-954b-906a6e50f686.png">
이런 느낌??

**Comment by daamable** [comment]
탐색 페이지 수정 
띠 이미지 넣기 : 박스 빼고 탐색 설명 글 보이게. 
전체적으로 탐색 이미지 이슈

**Comment by daamable** [comment]
탐색 메세지 가리기 버튼으로 넓히기

**Comment by daamable** [comment]
<img width="1048" alt="스크린샷 2019-03-12 오후 3 15 48" src="https://user-images.githubusercontent.com/39326928/54178600-c24e1580-44d9-11e9-9e25-67aa874356a5.png">


Class 계층 / 아래로 스크롤할 때 따라오게 하기? 

- 썸네일도 검색과 목록 같게
