### ISSUE TITLE
[관리 : 요청 목록] 시, 분, 초 중 '초' 삭제  

### ISSUE THREAD

**Issue by daamable** [seoul-metropolitan-archives/sdaweb#64]
- 2뎁스에 붙어있는 설명을 페이지 제목 하위로 옮기기 또는 마우스오버로 뜨게하기? 
- 요청목록 등 필드 추가 요청 받음 
- 좌우 컨테이너 늘리거나 해서 필드 최대한 보이도록 
- 목록 엑셀로 다운로드 기능 
- 등록일 시분초 빼기

**Comment by woonjjang** [comment]
좌우 컨텐이너 정리 완료(03.12)

**Comment by daamable** [comment]
<img width="293" alt="스크린샷 2019-03-12 오후 3 19 10" src="https://user-images.githubusercontent.com/39326928/54178763-338dc880-44da-11e9-9563-12a285835d6d.png">


- 오류신고 목 / 록 
- 이미지타일관리> : 겹쳐짐

**Comment by daamable** [comment]
![스크린샷 2019-03-15 오후 7 53 47](https://user-images.githubusercontent.com/39326928/54426797-0f411e80-475c-11e9-9ba6-d569bf0fe973.png)

- 요청 목록 시간 표현 형태를 시, 분 까지만 살린다.

**Comment by daamable** [comment]
[요청 목록] 현재 '보관함' 차단됨 
- 파일/아이템 기술 페이지 > 보관함 추가 
- 내 계정 or (로그인 한 상태의) GNB > 보관함 > 보관된 목록 확인


28일 임시 개관 전까지 요청 전체, 견학 신청 닫혀짐
