### ISSUE TITLE
(2일) [관리 : 포스트관리] 에디터  

### ISSUE THREAD

**Issue by daamable** [seoul-metropolitan-archives/sdaweb#66]
- 에디터 불편 or 상용? 
- 이미지 사이즈 값 : 직접 입력? / 숫자 입력칸 너무 작음 등 불편함 
- 제목 ... 많고 폰트 큼 / 목록 좁음
- 포스트 숫자 헷갈림 : 영역별 숫자로 재설정?

**Comment by daamable** [comment]
![스크린샷 2019-03-15 오후 8 23 58](https://user-images.githubusercontent.com/39326928/54428258-47e2f700-4760-11e9-8fba-4a8470945ffb.png)


- 미리보기를 비롯해서 이미지 첨부가 어렵다. 그래서 글 작성에 어려움이 있을 것으로 예상된다. 
- 하지만 이는 오픈 이슈는 아니고, 장기적으로 수정하는 것이 좋다고 판단된다.

**Comment by daamable** [comment]
- 에디터 폼의 전면 수정은 공수가 많이 드는 작업이므로 2019년 사업에 포함하는 것을 제안
- 28일까지 기능 구현은 가능하나 test 때문에 28일 넘어갈 가능성

**Comment by daamable** [comment]
상세화면에 첨부파일 다운로드 추가

**Comment by mozodev** [comment]
<img width="664" alt="스크린샷 2019-04-08 오후 3 44 50" src="https://user-images.githubusercontent.com/1661950/55703704-4f22bb00-5a15-11e9-957a-dc77be91bffd.png">
완료
