### ISSUE TITLE
관리 : 회원관리 

### ISSUE THREAD

**Issue by daamable** [seoul-metropolitan-archives/sdaweb#68]
- 이메일 링크 무엇?
- 회원가입 시 스스로 유형 선택해야 함
 : 잘못된 정보로 들어올 경우? 사용자 동선 별 구글 애널리틱스 스크립트 부여 
 : 회원유형 추가? 정책 이슈

**Comment by woonjjang** [comment]
필드 정리는 제가 한 번에 모아서 정리 요청할께요.

**Comment by daamable** [comment]
[다음 사업]

**Comment by daamable** [comment]
- 회원가입 시 회원 유형을 선택한다. 10회 로그인 이후 회원유형을 선택하도록 유도한다. 
- 회원 유형을 설정한다. (n개)
- 회원 중 특정 게시판을 관리할 수 있는 권한을 부여한다.

**Comment by daamable** [comment]
https://app.moqups.com/ddevc2Sl0I/edit/page/a3a7524e2

**Comment by mozodev** [comment]
완료

**Comment by mozodev** [comment]
http://52.79.195.15/user/register

**Comment by mozodev** [comment]
권한별 입력 제외한 가입, 관리 화면까지 완료

**Comment by daamable** [comment]
회원 유형 중복 체크

**Comment by daamable** [comment]
- 회원 목록 내 유형 필터
- 가입 날짜 : 날짜까지.
- 회원 유형 : 2개까지 수정 가능

**Comment by daamable** [comment]
탭 추가 : 관리담당자
- 중간관리자 이상을 대상으로, 각 게시판 별 권한 조정 가능한 테이블

**Comment by daamable** [comment]
이메일 발송과 연결

**Comment by daamable** [comment]
중간관리자 - 컬렉션 업로드 권한 부여

**Comment by daamable** [comment]
1) 회원유형 2개 선택가능 
2) 가입날짜에 시분초 빼기 
3) (가장 중요) 회원권한 중 ‘중간관리자’ : 컬렉션 관리의 CU, 본인 쓴 글의 D 기능만 부여  
4) 업무담당자 관리 : 우선 보류하는 것으로 얘기해보기 
- https://app.moqups.com/ddevc2Sl0I/edit/page/a3a7524e2
