### ISSUE TITLE
(3일) 가이드 관리 : 조사/연구가이드  (스타일 지정 - 생성시에)

### ISSUE THREAD

**Issue by daamable** [seoul-metropolitan-archives/sdaweb#69]
- 새로 추가 버튼 없음
- 리서치가이드 현재 에디터로 이전과 같은 컨셉 입력 가능? 
- 가이드 내 버전 보기 등 판단 
- 소스코드 복사 후 수정 가능 
- 박스 나눠서

**Comment by daamable** [comment]
전면 수정은 다음 사업 때 반영
현재 상황에서 입력하기 좋은 방식으로 수정 요청

**Comment by daamable** [comment]
열린 상태를 최초 상태로 수정

**Comment by mozodev** [comment]
완료
