### ISSUE TITLE
[기록] 사진 컴포넌트 연결의 문제

### ISSUE THREAD

**Issue by woonjjang** [seoul-metropolitan-archives/sdaweb#7]
경로에 adata02라고 되어있는 부분의 문제(실서버)

**Comment by daamable** [comment]
[해결된 이슈] 내용 확인 
- 기록 컴포넌트 이슈 
- 엔진의 행정, 수집 기록 폴더링과 사진 기록 폴더의 폴더 구조 체제가 달라서, 사진 기록이 실서버에서 뜨지 않았음
- 현재는 사진, 행정, 수집 기록물일 때 각각 경로값을 설정하여 해결
