### ISSUE TITLE
[관리 : 이용자 참여관리] 태그 삭제 후  

### ISSUE THREAD

**Issue by daamable** [seoul-metropolitan-archives/sdaweb#71]
- 태그 관리 
 : 정책결정 필요 
 : 태그 신고 내역 후 삭제 / 유지

**Comment by woonjjang** [comment]
신고된 태그 가운데 관리팀이 태그 접근 막기(태그가 대중에게 보이지 않도록 해야겠다고 변경)를 하면 
- 아이템 세부에서 보이지 않음. 
- #태그 경로에 접근이 안 됨. (개인 / 사용자 전체)
- 마이페이지 #태그 목록에서도 사라짐.

**Comment by daamable** [comment]
[태그 삭제 이후 시나리오] 
- 이상한 태그가 발생할 경우, 관리자/이용자는 태그를 신고한다.
- 태그가 신고되면 즉시 태그는 아이템에서 보이지 않고, 관리자의 태그 관리 영역 목록에 신고된 태그가 올라온다. 
- 그러나, 여전히 신고된 태그로 묶여진 태그 화면은 삭제된 건 아니다. 
[정책 결정 point]
1) 신고된 태그의 태그 화면은 : 접근할 수는 있게 한다. / 접근하지 못하게 한다. / 삭제한다.   
2) 태그가 신고되면 마이페이지 리스트에서 : 유지한다. / 접근하지 못하게 한다. / 삭제한다.

**Comment by daamable** [comment]
[태그 삭제 이후 시나리오]

- 관리자 태그 화면에는 등록된 태그 목록, 태그의 수정/삭제 기능, 태그의 상태값(등록/삭제/신고)이 표현되는 목록이 존재한다. 
 **: 현재 목록에 (방금 말한) 상태값 필드를 추가한다**
  
- 이용자가 태그를 등록한다. 
- 이상한 태그가 발생할 경우, 이용자는 태그를 신고할 수 있다. 관리자는 태그를 삭제/유지할 수 있다. (태그가 삭제되면 태그페이지도 삭제된다)  
- 내 계정에서는 태그의 상태값(등록/삭제/신고) 현황을 확인할 수 있다. 태그가 삭제/신고되면 내 계정에서 확인할 수 있다.
 **: 내 계정 > 태그 목록에 상태값(등록/삭제/신고) 열을 추가한다. 관리 목록의 상태값과 연동되어있다.** 

- 태그가 신고되면, 즉시 태그는 아이템에서 보이지 않고, 관리자의 태그 관리 영역 목록에 신고된 태그가 올라온다.
 - 내 계정에서는 신고된 태그라는 상태값만 변경된다. 
 - 관리자가 태그를 삭제하면 내 계정에서는 삭제된 태그라고 상태값이 변경된다. 
 **: 태그가 신고되면, 태그는 보이지 않는다. 태그의 상태값은 (등록->)신고로 변경된다.** 

- 관리자는 신고된 태그를 판단하여 해당 태그의 삭제/유지를 결정한다. 
 - 태그 삭제/유지 판단 결정을 태그를 단 사람에게 알린다. 

- 한번 삭제된 태그는 다시 달리지 않는다. **(기능구현 어려운지 확인. 일종의 블랙리스트. 필터링 기능 역할)** 
 - 삭제된 태그는 복원할 수 있다. 
 - 모든 로그는 삭제하지 않는다. 
 - [기술 확인] 만일 관리자가 태그를 삭제해도 복원이 가능하다면 **태그 페이지를 삭제한다.** (불필요한 태그 페이지를 계속 유지해야 하는가에 대한 문제) 
 - [기술 확인] 그런데 태그를 정말 삭제하면 복원이 불가능하다면, 그냥 이용자가 접속하지만 못하게 한다.   


[정책 결정 point]
신고된 태그의 태그 화면은 : 접근하지 못하게 한다. (url은 유지한다) 
태그가 신고되면 마이페이지 리스트에서 : 유지한다.

[다음 사업] 
- 태그 필터 기능을 단다.

**Comment by daamable** [comment]
https://app.moqups.com/ddevc2Sl0I/edit/page/a70ad8621

**Comment by daamable** [comment]
목업 수정 https://app.moqups.com/ddevc2Sl0I/edit/page/a70ad8621
