### ISSUE TITLE
로그인 화면 깨짐현상

### ISSUE THREAD

**Issue by kimyonghyun123** [seoul-metropolitan-archives/sdaweb#73]
![스크린샷 2019-03-11 오후 5 38 19](https://user-images.githubusercontent.com/48339928/54110339-79885500-4424-11e9-97b3-c90943160dc7.png)

**Comment by kimyonghyun123** [comment]
회원가입 비밀번호 초기화 버튼 깨짐현상

**Comment by css3studio** [comment]
http://52.79.195.15/user/login 수정함
