### ISSUE TITLE
검색결과시 오른쪽 배너 영역 변경 및 번체적인 스타일 변경

### ISSUE THREAD

**Issue by kimyonghyun123** [seoul-metropolitan-archives/sdaweb#75]
![screencapture-52-79-195-15-site-search-2019-03-11-18_02_57](https://user-images.githubusercontent.com/48339928/54111718-ea7d3c00-4427-11e9-8c45-4f19c2ace609.png)

**Comment by kimyonghyun123** [comment]
![Uploading 검색결과 영역 수정.jpg…]()

**Comment by css3studio** [comment]
http://52.79.195.15/site-search?search_option=0&query=%EC%84%9C%EC%9A%B8%EC%8B%9C
