### ISSUE TITLE
[이용자 도움말 > 시민을 위한 도움말] 링크 수정 / 화면 뷰 수정 

### ISSUE THREAD

**Issue by daamable** [seoul-metropolitan-archives/sdaweb#77]
<img width="882" alt="스크린샷 2019-03-12 오후 1 43 24" src="https://user-images.githubusercontent.com/39326928/54175114-ece5a180-44cc-11e9-9215-897032cf6ca0.png">

링크 url 없애고 문구로 넣기 / 색깔 뺀다

**Comment by daamable** [comment]
<img width="879" alt="스크린샷 2019-03-12 오후 1 45 46" src="https://user-images.githubusercontent.com/39326928/54175174-274f3e80-44cd-11e9-99af-e6d481f01ed5.png">


오픈 되어있는게 닫히지 않음

**Comment by daamable** [comment]
![스크린샷 2019-03-15 오후 7 26 22](https://user-images.githubusercontent.com/39326928/54425268-3bf33700-4758-11e9-9589-5510aacb39d9.png)


링크 색깔 빼기

**Comment by daamable** [comment]
- [이용자 도움말]의 모든 페이지가 아래, 위 버튼이 둘다 닫히거나, 열릴 수 있어야 한다. 

@css3studio

**Comment by daamable** [comment]
- [이용자 도움말]의 모든 링크들도 밑줄로만 통일 부탁드립니다. (볼드, 색깔 X)

**Comment by css3studio** [comment]
http://52.79.195.15/user-guide/28

**Comment by daamable** [comment]
크롬, 사파리 최종 확인하였습니다. 이슈를 닫습니다.
