### ISSUE TITLE
[Main] 회원가입 후 로그인 시 다시 회원가입 창이 뜨는 현상

### ISSUE THREAD

**Issue by daamable** [seoul-metropolitan-archives/sdaweb#78]
- 회원가입 시 이메일, 비밀번호 빈 칸 상태로 회원가입 버튼 누르면 404 에러 뜨는 경우

**Comment by mozodev** [comment]
http://52.79.195.15/user/register 완료

**Comment by daamable** [comment]
- 회원가입을 하고, 로그인 창이 떠서 로그인을 한 뒤, 바로 다시 회원가입 창이 뜨는 문제
