### ISSUE TITLE
[문의] 워딩, 링크 수정  

### ISSUE THREAD

**Issue by daamable** [seoul-metropolitan-archives/sdaweb#79]
<img width="1044" alt="스크린샷 2019-03-12 오후 1 56 48" src="https://user-images.githubusercontent.com/39326928/54175582-bf99f300-44ce-11e9-9333-b30b814fcb41.png">

**Comment by daamable** [comment]
<img width="922" alt="스크린샷 2019-03-15 오후 2 30 13" src="https://user-images.githubusercontent.com/39326928/54410445-dcccfc80-472e-11e9-9590-2efd282492e6.png">


일반문의 부분 링크도 기존 링크 방식(글자로 url 연결하고 파란색 밑줄 넣기)로 설정하는 게 좋을 것 같습니다. 
워딩 부분 약간 수정 필요한 부분도 있습니다.  
<공공기록관리에관한법률> -> <공공기록물 관리에 관한 법률>

서울시 정보소통광장에서 **'서울기록원'으로 검색**하시면 더 많은 정보를 얻을 수 있습니다. 

아래 링크를 저 '서울기록원'으로 검색 워딩에 넣으면 될 것 같습니다. 
http://opengov.seoul.go.kr/search?searchKeyword=서울기록원
그리고 밑줄 넣고, 파란색은 빼주세요. (볼드 X)

**Comment by daamable** [comment]
<img width="260" alt="스크린샷 2019-03-15 오후 8 41 05" src="https://user-images.githubusercontent.com/39326928/54429022-b7f27c80-4762-11e9-92ef-231550265d6a.png">


시설 견학 담당 -> 보존 시설 견학 담당

**Comment by css3studio** [comment]
"일반문의 부분 링크도 기존 링크 방식(글자로 url 연결하고 파란색 밑줄 넣기)로 설정하는 게 좋을 것 같습니다."
죄송한데, 이부분 좀 더 자세히 알려주세요~

혹시, <공공기록물 관리에 관한 법률> 이 텍스트에 링크를 넣어달라는 말씀이신가요?

**Comment by daamable** [comment]
네 맞습니다. (질문 달아주시면 저도 답변 달겠습니다)

**Comment by css3studio** [comment]
http://52.79.195.15/about/inquiry
넵 처리하였습니다

**Comment by daamable** [comment]
<img width="727" alt="스크린샷 2019-03-18 오후 3 52 49" src="https://user-images.githubusercontent.com/39326928/54511938-ec01b380-4995-11e9-8d05-798351237456.png">

반영해주셔셔 감사합니다. 
근데 제가 한번 더 확인해보니 조금 더 수정할 것이 있네요 ㅠ
---

서울기록원은 <공공기록물 관리에 관한 법률> 제11조(지방기록물관리기관) 제1항과 <서울특별시 기록물 관리에 관한 조례> 제2장(서울기록원의 설치 및 운영) 제5조에 근거하여 설치, 운영하고 있습니다. 

위 법률과 조례는 국가법령정보센터를 통해 확인할 수 있습니다. 

**<공공기록물 관리에 관한 법률> 
(이하는 현행과 동일) 

-- 

- <공공기록관리에관한법률> --> <공공기록물 관리에 관한 법률> 
- ~~ 확인할 수 있습니다. 
 (아래 한 줄 띄우기)

**Comment by css3studio** [comment]
수정사항
1.<공공기록관리에관한법률> --> <공공기록물 관리에 관한 법률> : 이미 반영되어 있음
2.~~ 확인할 수 있습니다. 아래 한줄띄우기 : 반영함
3. 링크 컬러 없앰 : 반영함
