### ISSUE TITLE
(4일) [아이템 다운로드] UI 수정 

### ISSUE THREAD

**Issue by daamable** [seoul-metropolitan-archives/sdaweb#81]
<img width="790" alt="스크린샷 2019-03-12 오후 2 24 42" src="https://user-images.githubusercontent.com/39326928/54176576-c32f7900-44d2-11e9-9e52-5a784afedf4e.png">

컴포넌트 파일 2개인데 '다운로드' 파일 누르면 앞 파일만 다운로드

**Comment by woonjjang** [comment]
파일에 대한 다운로드 정책이 정해져있지 않습니다. 
1. 상단에 노출되어 있는 파일명을 클릭하면 개별 파일이 다운로드 된다. (작은 다운로드 버튼을 넣어주면 어떨까요 ?)
2. 하단에 다운로드 버튼을 누르면 zip파일을 만들어주는 것은 압축파일을 풀지 못 하는 사용자가 있으므로 접근성에 위배된다고 보입니다. 
3. 현재 파일이 다수가 있는 경우는 없으니 다운로드(파일명 - 아주 작은 글씨로), 다운로드(파일명 - 아주 작은 글씨로)

**Comment by woonjjang** [comment]
http://52.79.195.15/item/1864885 적용완료.

**Comment by daamable** [comment]
![스크린샷 2019-03-15 오후 7 43 52](https://user-images.githubusercontent.com/39326928/54426271-bde45f80-475a-11e9-9e64-e278d1a4df25.png)

![스크린샷 2019-03-15 오후 7 45 00](https://user-images.githubusercontent.com/39326928/54426319-d5234d00-475a-11e9-8d02-cc12df09910d.png)

- 원문정보 박스 없애고, 기술 페이지 맨 밑에 정보소통광장 다운로드 처럼 넣는다. 
- 파일 제목은 RM 문제이기에 현재 건드릴 수 없다. 
- 원문 뷰어는 지금 해결할 수 없다. 
- 이 부분은 중요한 UI 이지만, 현재 원문 있는 파일이 별로 없어서 일단 오픈 이슈로 넣지 않는다.

**Comment by daamable** [comment]
[이슈 정리] 
- 현재 컴포넌트가 이미지, PDF 파일인 경우 원문 뷰어로 뷰잉이 가능하다.
- 컴포넌트가 한글 파일인 경우 원분 뷰어로 보여주지 않기로 결정했다. (기록원과 사전 결정 함)
 : 한글 파일의 뷰어 방식 및 다운로드에 대한 정책적 결정이 필요하다. (현재 상태 유지, 또는 hwp->pdf 파일 변환 후 뷰어 등)
- 현재 배치된 n개의 다운로드 버튼은, 실제 컴포넌트 maximum이 5개 이상인 것이 없으므로 현재 5개 버튼까지 표현이 가능할 것으로 판단했다. 
- 다운로드는 통계 로그와 연결되는데, 현재 다운로드 통계 로그는 아이템 단위로 측정하고, 컴포넌트 단위로 측정하지 않는데 향후 이에 대한 이슈가 발생할 수 있으므로 역시 정책 결정이 필요하다.

**Comment by daamable** [comment]
[오류] 로그인 하지 않았는데 다운로드가 되는 경우가 발생합니다. 
@mozodev

**Comment by daamable** [comment]
- 원문이 PDF가 아닌 것들(hwp 등)은 원문으로 보여주지 않고, 정보소통광장 형식(UI)의 다운로드만 제공한다.
- 컴포넌트 단위 통계 정책에 대한 확인 요청(임태원 주임님)

**Comment by daamable** [comment]
https://app.moqups.com/ddevc2Sl0I/edit/page/a07cc6d53

**Comment by mozodev** [comment]
<img width="933" alt="스크린샷 2019-04-04 오후 9 37 43" src="https://user-images.githubusercontent.com/1661950/55556240-05d72080-5722-11e9-9fa9-69ae873609ce.png">

**Comment by daamable** [comment]
i 아이콘만 뺀다

**Comment by mozodev** [comment]
완료
