### ISSUE TITLE
(4일) [검색 결과값 저장 기능] 

### ISSUE THREAD

**Issue by daamable** [seoul-metropolitan-archives/sdaweb#82]
URL 관리 안내 필요 
2019년?  

- 28일 to do 
엑셀 목록 다운로드, 인쇄, 저장

**Comment by daamable** [comment]
로그인 안 해도 버튼 보이고 실제 버튼 작동 안함

**Comment by daamable** [comment]
- 검색 결과 값을 엑셀로 다운로드 하는 기능, 즉 버튼을 만들어서 붙인다. 
- 내 계정에서 나의 검색 결과 로그를 확인하는 페이지(검색 결과 로그)를 만든다.

**Comment by daamable** [comment]
(로그인 한 이용자가 검색 결과 목록을 저장한다)
검색 결과 목록에서 
- 목록 다운로드 (moqup)
- 목록 출력 (moqup) 
- 저장 (moqup)

내 계정에서 나의 검색 결과를 확인하는 화면이 필요하다.

**Comment by woonjjang** [comment]
화면을 새로 그린다.

**Comment by daamable** [comment]
https://app.moqups.com/ddevc2Sl0I/edit/page/ab652f05c

**Comment by daamable** [comment]
인쇄 UI 수정 
[서울기록원 결과값.pdf](https://github.com/seoul-metropolitan-archives/sdaweb/files/3037308/default.pdf)

**Comment by daamable** [comment]
- 썸네일에 alt 값을 추가하고, 화면에 보이지 않는다.

**Comment by mozodev** [comment]
완료

**Comment by daamable** [comment]
[목록 다운로드] 에서 마우스 오버 시 표시 
"검색 결과 10,000개 이하인 경우에만 다운로드가 가능합니다"

**Comment by daamable** [comment]
- 목록 즐겨찾기에서 쿼리 이름 변경 : query -> 검색결과, 순서 조정 (쿼리 제일 먼저, 패싯 순서)
- 목록 즐겨찾기 두 번째 탭

**Comment by daamable** [comment]
검색조건 표현 (우리말) 및 순서 

- Query : 검색어
- Regclass : 구분 
- Levelname : 기술계층 
- Creator : 생산자 
- Date : 날짜 
- Regtype : 기록 유형

**Comment by mozodev** [comment]
완료
