### ISSUE TITLE
[+design] 로고 옆에 베타 표시

### ISSUE THREAD

**Issue by seoularchives** [seoul-metropolitan-archives/sdaweb#83]
1. 메인 로고 옆에 현재 베타 (베타 영어단어는 이미지 확인해서 써야 함.)

**Comment by kimyonghyun123** [comment]
![베타 라벨 예시](https://user-images.githubusercontent.com/48339928/54336882-aa5cca00-4670-11e9-9cc7-be47bc883667.jpg)
<img width="36" alt="beta img" src="https://user-images.githubusercontent.com/48339928/54336883-aaf56080-4670-11e9-824d-0baa5eb8d470.png">

**Comment by css3studio** [comment]
`<div` class="lg01 beta"><a `href="/">서울기록원</a></div>`
추후 beta 클래스명을 빼버리면 됩니다
