### ISSUE TITLE
[탐색] 페이지 디자인, 워딩 수정 

### ISSUE THREAD

**Issue by woonjjang** [seoul-metropolitan-archives/sdaweb#84]
http://52.79.195.15/browse-class

상단에 전달한 사진 height를 200px~ 300px정도만 붙임.
탐색 설명글은 숨길 수 있도록 함. (하단 텍스트가 읽히는게 중요함.)

**Comment by woonjjang** [comment]
![DSC01246](https://user-images.githubusercontent.com/6022883/54291006-4219d400-45ef-11e9-8314-03659e9d27f5.JPG)
![DSC01257](https://user-images.githubusercontent.com/6022883/54291007-4219d400-45ef-11e9-8f2a-1c04bd06f794.JPG)

**Comment by woonjjang** [comment]
![DSC01246](https://user-images.githubusercontent.com/6022883/54291006-4219d400-45ef-11e9-8314-03659e9d27f5.JPG)
![DSC01257](https://user-images.githubusercontent.com/6022883/54291007-4219d400-45ef-11e9-8f2a-1c04bd06f794.JPG)

**Comment by kimyonghyun123** [comment]
![탐색변경](https://user-images.githubusercontent.com/48339928/54348507-7e4f4200-468c-11e9-91d0-8735841315fc.jpg)

**Comment by css3studio** [comment]
http://52.79.195.15/browse-class

**Comment by daamable** [comment]
![스크린샷 2019-03-15 오후 8 06 59](https://user-images.githubusercontent.com/39326928/54427463-e752ba80-475d-11e9-9476-fd5c1a3638e6.png)

@css3studio 현민님, 탐색 버튼 UI는 출처별 기록 보기의 버튼으로 컨펌 받아서, 아래 위 버튼 그룹들도 똑같이 적용해 주시면 좋겠습니다. 
@kimyonghyun123 퍼블리싱 이후 확인 부탁드립니다.

**Comment by daamable** [comment]
![스크린샷 2019-03-15 오후 8 08 09](https://user-images.githubusercontent.com/39326928/54427519-0fdab480-475e-11e9-8fbe-9a48acc5bc0e.png)

탐색 부분 워딩 확인(임태원 주무관님 기준)

**Comment by daamable** [comment]
[탐색 워딩 수정] 확인 완료 https://docs.google.com/document/d/1E34hwKMPXyRfk6zhZweL3frJEbzTEMKz6RN5mFWg23Q/edit#] 

아카이브에서 기록을 찾는 것은 PC에서 파일을 찾는 것과 크게 다를 바 없습니다. 찾는 파일이 어느 폴더에 있는지 찾기 힘들 때는 ‘검색’을 활용합니다. 하지만 주제, 사안, 시간순 등 일정한 질서를 부여하여 폴더를 정리하면, 탐색기를 통해서 원하는 파일의 위치를 쉽게 찾아갈 수 있습니다. 기록 카탈로그(catalog)는 기록이 생산되고 구성된 맥락에 따라 PC에서 폴더를 구성하듯이 기록을 계층별로 정리한 형태이며, 정리된 기록의 각 묶음별로 상세기술 정보를 제공함으로써 맥락에 따른 기록의 탐색을 제공합니다.

(펼쳤을 때 보이는 나머지 부분)

※서울특별시 시정기록 사본과 수집한 시민기록을 대상으로 카탈로그 베타버전을 제작했고 이를 공개합니다. 앞으로 서울기록원 선별 수집 및 이관한 중요기록물로 지속적인 카탈로그 제작을 통해 보다 쉽게 기록을 탐색할 수 있도록 고도화 할 예정입니다.

**Comment by css3studio** [comment]
http://52.79.195.15/browse-class
워딩수정 및 버튼 스타일 변경

**Comment by daamable** [comment]
반영 감사드립니다. 
한번 더 확인해 주실 부분 말씀드립니다. 

- 마우스 오버 시 best라고 말씀드린 중간 부분은 파란색으로 변하는데, 아래 위 부분은 검은색으로 변합니다. 파란색으로 변경을 부탁드립니다. 
- 타블렛으로 비율 조정 시 버튼이 깨지는 문제를 확인했습니다. 이 부분도 확인 부탁드립니다.

**Comment by daamable** [comment]
<img width="389" alt="스크린샷 2019-03-19 오전 9 22 40" src="https://user-images.githubusercontent.com/39326928/54572027-92969480-4a28-11e9-8e48-b2fce40b47e1.png">

**Comment by css3studio** [comment]
1.마우스 오버시 색상 변경
2.모바일 모드시 깨지는 문제 수정
