### ISSUE TITLE
[주요 경과] 워딩 수정

### ISSUE THREAD

**Issue by woonjjang** [seoul-metropolitan-archives/sdaweb#85]
![스크린샷 2019-03-12 오후 1 22 00](https://user-images.githubusercontent.com/6022883/54291412-de43db00-45ef-11e9-9ab8-ef012fb13291.png)
![스크린샷 2019-03-12 오후 1 24 30](https://user-images.githubusercontent.com/6022883/54291413-dedc7180-45ef-11e9-880b-9dd771a3de96.png)
![스크린샷 2019-03-12 오후 1 25 00](https://user-images.githubusercontent.com/6022883/54291414-dedc7180-45ef-11e9-89c4-ec6d5a20b0d7.png)
![스크린샷 2019-03-12 오후 1 25 30](https://user-images.githubusercontent.com/6022883/54291417-df750800-45ef-11e9-8e39-49165641de03.png)
![스크린샷 2019-03-12 오후 1 27 20](https://user-images.githubusercontent.com/6022883/54291420-e00d9e80-45ef-11e9-826b-43e7198cf9ec.png)
![스크린샷 2019-03-12 오후 1 30 45](https://user-images.githubusercontent.com/6022883/54291421-e00d9e80-45ef-11e9-81f9-0dab2398216e.png)
![스크린샷 2019-03-12 오후 1 33 32](https://user-images.githubusercontent.com/6022883/54291424-e00d9e80-45ef-11e9-9423-89565687e567.png)
![스크린샷 2019-03-12 오후 1 36 16](https://user-images.githubusercontent.com/6022883/54291425-e0a63500-45ef-11e9-9a87-64a0ad57c7e7.png)
![스크린샷 2019-03-12 오후 1 36 42](https://user-images.githubusercontent.com/6022883/54291429-e0a63500-45ef-11e9-9314-a81acd0f5e19.png)
![스크린샷 2019-03-12 오후 1 49 28](https://user-images.githubusercontent.com/6022883/54291431-e13ecb80-45ef-11e9-9c86-12c3706f8403.png)
![스크린샷 2019-03-12 오후 1 53 56](https://user-images.githubusercontent.com/6022883/54291432-e13ecb80-45ef-11e9-8536-9c324f67038a.png)
![스크린샷 2019-03-12 오후 2 31 43](https://user-images.githubusercontent.com/6022883/54291433-e1d76200-45ef-11e9-901b-cdc91ba0aef0.png)
![스크린샷 2019-03-12 오후 2 57 51](https://user-images.githubusercontent.com/6022883/54291435-e1d76200-45ef-11e9-918f-faf548164111.png)

**Comment by woonjjang** [comment]
![스크린샷 2019-03-12 오후 1 27 20](https://user-images.githubusercontent.com/6022883/54397342-7b3e6b00-46f9-11e9-9ba9-4562502c11b2.png)
Validation 메세지 수정 요청 @css3studio

**Comment by woonjjang** [comment]
<img width="1331" alt="추진경과 정렬" src="https://user-images.githubusercontent.com/6022883/54397403-afb22700-46f9-11e9-8c80-0af016b7595b.png">

**Comment by css3studio** [comment]
http://52.79.195.15/about/progress

**Comment by daamable** [comment]
<img width="547" alt="스크린샷 2019-03-15 오후 2 02 29" src="https://user-images.githubusercontent.com/39326928/54409604-0c7a0580-472b-11e9-8411-f3fe87f4a374.png">

기록물기록물관리기관 -> 영구기록물관리기관

**Comment by daamable** [comment]
<img width="495" alt="스크린샷 2019-03-15 오후 2 05 01" src="https://user-images.githubusercontent.com/39326928/54409658-55ca5500-472b-11e9-8575-ce76d053e453.png">

[아래] 버튼 의 크기를 줄여주세요. 

@kimyonghyun123 부탁드립니다!

**Comment by daamable** [comment]
<img width="667" alt="스크린샷 2019-03-15 오후 2 06 00" src="https://user-images.githubusercontent.com/39326928/54409702-798d9b00-472b-11e9-91f2-b99410ba8db2.png">


연도숫자 뒤 글자들의 전체 선 라인 한번만 더 맞춰주시면 좋겠습니다. 약간씩 어긋나는 느낌이네요 ㅠㅠ

**Comment by daamable** [comment]
![스크린샷 2019-03-15 오후 8 11 07](https://user-images.githubusercontent.com/39326928/54427669-7cee4a00-475e-11e9-86b0-b0c3ecf415a2.png)



- 연도 뒤 전체적으로 공간 내고 라인 맞춘다. 
- [연구보고서 보기] 이 부분 모두 워딩 밑줄 링크로 준다. 
- 버튼 크기를 글씨 크기 정도로 줄인다.

**Comment by daamable** [comment]
![스크린샷 2019-03-15 오후 8 12 26](https://user-images.githubusercontent.com/39326928/54427726-aa3af800-475e-11e9-9f72-496ef3710e96.png)


2013.06.14 로 0 하나 넣기

**Comment by css3studio** [comment]
수정완려

**Comment by daamable** [comment]
<img width="467" alt="스크린샷 2019-03-18 오후 10 11 20" src="https://user-images.githubusercontent.com/39326928/54532296-c642d180-49ca-11e9-93e3-b1fc332cc393.png">

중간 부분 '영구기록물관리기관' 단어를 붙여주시면 좋겠습니다.

**Comment by css3studio** [comment]
1.'영구기록물관리기관' 단어를 붙여주시면 좋겠습니다. -> 반영함
2. 링크를 워딩에 반영 -> 반영함
3. 링크컬러 없앰 -> 반영함
