### ISSUE TITLE
[파일서버 관련] 추가 마운트 필요(엔진 수준)

### ISSUE THREAD

**Issue by woonjjang** [seoul-metropolitan-archives/sdaweb#87]
파일서버 관련
파일 서버 파티션 구성

루트 파티션 91GB
5GB 사용 / 81GB 여유

/nfs/data	
1018GB
730GB / 289GB

추가 디스크 마운트 필요

**Comment by daamable** [comment]
@seoularchives 확인 부탁드립니다.
