### ISSUE TITLE
발간번호 부여 기능

### ISSUE THREAD

**Issue by woonjjang** [seoul-metropolitan-archives/sdaweb#89]

**Comment by daamable** [comment]
[현재 상황] 
- 발간번호 관련 관리 기능은 만들어져있음. 관리 페이지가 붙여져있지는 않음
- 박지현 주무관님과 협의 
- 기능 구현은 어렵지 않으나, test가 많이 필요하므로, 3/28 이후로 넘어갈 가능성

**Comment by daamable** [comment]
- 발간번호 화면의 컨펌을 받는다(임태원 주무관님) 
- 오픈 이후, 기능 관련하여 임태원, 박지현 주무관님 미팅 통해 최종 컨펌 받는다.
- 기능 구현

**Comment by daamable** [comment]
[발간번호 이슈 정리] 
3.21 
서울기록원 임태원 주무관, 박지현 주무관
슬로워크 장대환 

**현재까지의 진행 상황** 

- 발간번호 관련 메인 페이지, 관리 페이지 만들어져 있음 
    - 관리 업무를 웹에서 할지, DB에서 할지에 대한 논의 이후 추후 개발 가능
- 정부간행물 발간등록 및 송부 페이지 http://52.79.195.15/gov-publications
    - 메인 화면에서 노출되어있지 않음 
    - 등록 신청 기능 및 페이지 만들어져 있음. 실제 등록하면 웹 DB에 쌓을 수는 있는 상황 
- 관리 > 요청 목록 > 정부간행물 발간등록 및 송부 http://52.79.195.15/html-v2-admin/UC38_admin_reg_publish_list.html
    - 웹에서 관리자가 관련 프로세스에 따라 관리할 수 있는 페이지 
    - 현재는 관리 단에서 등록 세부페이지를 볼 수 있음 http://52.79.195.15/html-v2-admin/UC38_admin_reg_publish_view.html
    - 그러나 실제 [신청], [번호생성], [반려], [처리완료] 등 기능 구현 개발은 멈춰있음 
- 현재까지의 화면은 모두 김승희 주임님 컨펌
- [참고] WEB 팀의 정부간행물 발간번호 등록 및 송부 관련 자료 https://drive.google.com/drive/folders/1a0Ef8t9dA918_KXTHdKxiwUULrDZ4MxG 

**확인사항**  
 1. 관리 영역 WEB? 엔진?
- 2018년 사업에서 김승희 주임님 등 컨펌된 사항은 해당 관리기능의 프론트 및 DB 저장기능을 만드는 일까지임
- 이후 관리를 실제 WEB에서 할지 엔진에서 할지에 대한 논의로 이후 개발 중단
- 웹에서 엔진으로 해당 데이터를 보내기 어려운 것으로 확인 
- 확인 : 추구 관리 영역 WEB? 엔진?
    - WEB에서 관리한다고 결정될 경우, 현재 개발된 페이지와 프로세스 등 고려하여 3.28 milestone으로 처리하고, test 포함하여 4월 초까지 개발될 수 있을 것으로 예상
    - 엔진에서 관리한다고 결정될 경우, 업무는 엔진으로 넘어가기 때문에 WEB 개발은 다음 사업에서 할 수 있을 것으로 전망 
 2. 발간번호 생성 프로세스 및 규칙 확인 
- 현재 WEB 팀에서 확보한 발간번호 업무 프로세스 및 생성 규칙에 따라 발간번호 생성하는 것으로 확인하고 있으나, 기록원 담당 주무관님과 맞는지 확인 필요 
- 프로세스 관련 추후 개발 사항 
    - 신청, 번호 생성, 반려, 처리완료 시 관리자/요청자에게 메일 및 내 계정에서 해당 내용 확인
 3. 정보공개정책과와 오픈 시점 전후 최종 DB 확보 필요 
- 서울기록원 개관 전까지 서울시의 발간번호 등록은 서울시 정보공개정책과가 서울시의 발간번호 신청을 모아 국가기록원에 한꺼번에 등록하는 것으로 알고 있음 
- 개관 전 최종 DB를 확보해야 웹 DB에 넣을 수 있음 
 4. 언제 해당 서비스를 하는가? 
- 5월 초로 알고 있음 
 5. 메뉴는 어디에 붙일 것인가?
- 현재 푸터 메뉴에는 표시되어 있지 않음
- 대국민 서비스가 아니고 대공무원 서비스이기 때문에, 메인화면에 노출되는 것보다 [문의] 등에서 설명 및 링크를 제공하는 형식으로의 안을 제안 
 6. 현재 고유 URL을 쓸 것인가?
- /gov-publications 
- 한번 더 확인

**Comment by daamable** [comment]
- 서비스 런칭 시기 : 2020.01.01 
- 대상 기관 : 서울시 본청, 산하기관, 출연기관 등 모두 (우선) 
- 발간번호 DB 확보 : 하반기에 전체 리스트 확보 예정 (즉, 리스트도 하반기)
**- 웹 노출은 하지 않는다. (무분별한 등록을 막을 수 있게)**
**- 신청 등록 반려 등 기능 구현 (3/28)** 
**- 관리자는 신청, 등록, 반려 등 모든 기능을 확인할 수 있다.** 
- 엔진 vs WEB (다음 사업 반영) 
**- URL 유지 (/gov-publications)**
- 엑셀을 통해 더미 데이터 업로드 (다음 사업)

**Comment by daamable** [comment]
https://app.moqups.com/ddevc2Sl0I/edit/page/a1ec02c96

**Comment by daamable** [comment]
목업 수정 https://app.moqups.com/ddevc2Sl0I/edit/page/a1ec02c96

**Comment by daamable** [comment]
상태값 이름 변경 : 접수대기, 반려, 처리중, 처리완료 (=번호생성 되었음)
