### ISSUE TITLE
[Main] [중요] [검색] 패싯 or / 패싯 계층 순서(시리즈-파일-아이템)

### ISSUE THREAD

**Issue by woonjjang** [seoul-metropolitan-archives/sdaweb#90]
패싯 순서 정렬에 관련해서 
 다른 곳들 봐도 모두 카운트 수 많은 순으로 정렬
정렬을 위해서 나쁜 코드를 쓰면서 정렬하는 것은 좋지 않다고 판단

**Comment by daamable** [comment]
- 생산연도 : 내림차순(최신순) 
- 나머지 : ㄱㄴㄷ순 
- 없음, 미상, 기타를 각 패싯 영역 맨 하단에 위치 
@mozodev

**Comment by daamable** [comment]
![스크린샷 2019-03-15 오후 8 21 40](https://user-images.githubusercontent.com/39326928/54428167-f33f7c00-475f-11e9-931e-1915bbcf79e5.png)


체크박스를 상세검색의 체크박스로 교체 

@css3studio

**Comment by daamable** [comment]
패싯 관련 
- 박스 내 or 문제 
- 시리즈 이하 계층, 즉 시리즈, 파일, 아이템에는 모두 분류값(주제, 출처, 컬렉션)이 목록 박스에 들어간다.
- 목록 박스 내 생산자도 다 표현되야 한다. 
- 온라인 열람 가능 / 온라인 열람 불가 : 둘 중 하나가 표현되어야

**Comment by daamable** [comment]
<img width="692" alt="스크린샷 2019-03-15 오후 8 52 47" src="https://user-images.githubusercontent.com/39326928/54429597-4ca9aa00-4764-11e9-95eb-11999eb76d7c.png">

목록 제목 과 연도 사이에 ,(컴마) 넣는다. 

@mozodev

**Comment by daamable** [comment]
[다음 사업] 
- 현재 탐색과 검색 동선이 나뉘고, 이에 따라 그 목록도 나뉘어있다. 
- 그러나 탐색이든 검색이든 결국 접근방식의 차이이고, 실제 두 방식으로 접근하면 모두 하나의 목록으로 도달한다. 
- 그러나 이 이슈는 현재 반영하기 어려우므로, 다음 사업에 반영하는 것이 좋겠다.

**Comment by css3studio** [comment]
체크박스를 상세검색의 체크박스(기본)로 교체하였습니다.

**Comment by css3studio** [comment]
http://52.79.195.15/search?search_option=1&query=%EC%84%9C%EC%9A%B8&regclass=%EA%B3%B5%EA%B3%B5%EA%B8%B0%EB%A1%9D%4001&query=a&levelname=item

**Comment by daamable** [comment]
> http://52.79.195.15/search?search_option=1&query=%EC%84%9C%EC%9A%B8&regclass=%EA%B3%B5%EA%B3%B5%EA%B8%B0%EB%A1%9D%4001&query=a&levelname=item

현민님 이 부분 반영이 사파리에서는 보이는데 크롬에서는 원래 상태로 보입니다. 확인 부탁드려도 될까요?

**Comment by mozodev** [comment]
두 가지 제외하고 모두 적용했는데요..
1. 박스 내 or 문제
=> 패싯 항목 or 는 지원되는데 UI 문제라 선택하고 버튼 클릭하지 않으면 어떻게 구현이 가능한지 모르겠음

2. 시리즈 이하 계층, 즉 시리즈, 파일, 아이템에는 모두 분류값(주제, 출처, 컬렉션)이 목록 박스에 들어간다.
=> 이게 예전에는 집합체, 아이템 모두 연결해서 줬는데 이제는 집합체까지만 연결했네요..
이러면 검색 쿼리를 대량으로 수정해야합니다. 시간이 좀 걸릴 수 있어요

**Comment by daamable** [comment]
패싯 버튼 이름 바꾸기 
refine : 필터 적용
clear : 초기화

**Comment by daamable** [comment]
워딩 수정 (엔진에서 먼저 수정되었는지 확인) 
공공기록 -> 시정기록 
시민기록 -> 민간기록

**Comment by daamable** [comment]
온라인열람 표시 : 아이템 레벨에서만 표현

**Comment by mozodev** [comment]
일단 수정 완료 워딩 수정 건은 코드 테이블에서 값을 수정했기 때문에 다음번 검색엔진 인덱싱이 완료되면 화면에 노출되기 시작할거에요.

**Comment by daamable** [comment]
검색화면 패싯 관련 UI 수정 
- '온라인 열람 가능 기록'를 패싯 바로 위로 옮긴다. 
- [적용] 버튼을 각 패싯박스 하단 마다 부여
- [초기화] 버튼을 현재 '온라인 열람 가능 기록' 위치로 이동
