### ISSUE TITLE
[Main] 시리즈 - 파일 계층 표시 

### ISSUE THREAD

**Issue by daamable** [seoul-metropolitan-archives/sdaweb#91]
<img width="510" alt="스크린샷 2019-03-15 오후 3 54 57" src="https://user-images.githubusercontent.com/39326928/54413905-bc0aa400-473a-11e9-9720-50667c911968.png">

시리즈에서 화살표 보임

**Comment by mozodev** [comment]
http://52.79.195.15/browse/4182
확인 결과
서울시 1950년대 경제.산업 분야 사진기록 1959 파일(철)이 클래스와 연결되지 않아서 발생한 문제
http://52.79.195.15/aggregation/4182

집합체의 상위 클래스가 없어서 오동작하는 상태. 기록을 바로잡을지 이게 맞는 상태면 코드 수정이 필요한 상황.

**Comment by mozodev** [comment]
일단 시리즈에서 화살표 안보이도록 수정 완료

**Comment by daamable** [comment]
이 이슈와 별개로, 현재 시리즈-파일-아이템으로 내려갈 때 계층이 안보이는 것 같습니다. 확인 부탁드립니다.

**Comment by mozodev** [comment]
캐시 문제였네요 수정했습니다.
http://52.79.195.15/browse/10134
http://52.79.195.15/item/1863752
