### ISSUE TITLE
[design] [소개] 서울기록원 3개년 운영계획 이미지 수정 

### ISSUE THREAD

**Issue by daamable** [seoul-metropolitan-archives/sdaweb#92]
<img width="337" alt="스크린샷 2019-03-15 오후 4 35 38" src="https://user-images.githubusercontent.com/39326928/54415731-836dc900-4740-11e9-8f57-81f952521714.png">

서울기록원 3개년 운영 계획 책 이미지 옆 흰색 라인 없애기 
서울시 정보소통광장에서 보기 버튼 사이즈와 책 가로 사이즈 맞추기

**Comment by kimyonghyun123** [comment]
![brochure img](https://user-images.githubusercontent.com/48339928/54510210-c2458e00-498f-11e9-8a8e-c498089d2ed6.png)

**Comment by daamable** [comment]
@css3studio 현민님 용님이 수정해 주신 부분 반영 부탁드립니다!

**Comment by css3studio** [comment]
http://52.79.195.15/about

**Comment by daamable** [comment]
<img width="218" alt="스크린샷 2019-03-18 오후 3 43 46" src="https://user-images.githubusercontent.com/39326928/54511596-c1632b00-4994-11e9-82d3-8181923c6b3c.png">

Safari에서는 수정된 것으로 잘 보이는데, Chrome에서는 이렇게 보입니다. ㅠㅠ 한번만 더 확인 부탁드려요.

**Comment by daamable** [comment]
크롬, 사파리 확인했고 이슈를 닫습니다.
