### ISSUE TITLE
[기능 및 조직 구성] 워딩 수정 

### ISSUE THREAD

**Issue by daamable** [seoul-metropolitan-archives/sdaweb#93]
<img width="990" alt="스크린샷 2019-03-15 오후 4 39 28" src="https://user-images.githubusercontent.com/39326928/54415874-05f68880-4741-11e9-9914-46e40a205d72.png">

첫 줄 두번째 점 지워주세요 ㅠㅠㅠㅠ

**Comment by daamable** [comment]
<img width="742" alt="스크린샷 2019-03-18 오후 3 40 50" src="https://user-images.githubusercontent.com/39326928/54511393-3f730200-4994-11e9-9d9e-66d155aa97c6.png">



- 유형별(점)매체별 : 여기 사이 다 붙이기
- 소독(점)훈증(점)탈산 처리 : 여기도 다 사이 붙이기

**Comment by daamable** [comment]
<img width="987" alt="스크린샷 2019-03-15 오후 4 43 00" src="https://user-images.githubusercontent.com/39326928/54416000-684f8900-4741-11e9-8b44-17a1ad5e6a43.png">

마지막 줄 
- 디지털 아카이브 구축(점)운영 (시스템 / 기록 업무)
  (시스템 : 김을지 주무관 / 기록 업무 : 임태원 주무관) 

여기도 띄어쓰기 부탁드려요!

**Comment by daamable** [comment]
<img width="972" alt="스크린샷 2019-03-15 오후 4 44 06" src="https://user-images.githubusercontent.com/39326928/54416044-91701980-4741-11e9-8311-3cf3a5606125.png">


마지막 줄 맨 끝 괄호 닫아주세요!

**Comment by mozodev** [comment]
수정했습니다.

**Comment by kimyonghyun123** [comment]
20x20px    아이콘은 13px로 부탁드립니다.

**Comment by daamable** [comment]
[28일 전후로 천천히 고쳐주셔도 됩니다]

![스크린샷 2019-03-19 오후 8 40 57](https://user-images.githubusercontent.com/39326928/54603298-4fb7d980-4a87-11e9-90b1-b083560cef77.png)

기록처분 -> 기록v처분

![스크린샷 2019-03-19 오후 8 41 38](https://user-images.githubusercontent.com/39326928/54603337-678f5d80-4a87-11e9-82fb-cc0e0ce740b3.png)

열람서비스 -> 기록v열람 

![스크린샷 2019-03-19 오후 8 42 05](https://user-images.githubusercontent.com/39326928/54603362-770ea680-4a87-11e9-989b-d138a53c79cf.png)

기록물 공개 -> 기록 공개

**Comment by daamable** [comment]
<img width="544" alt="스크린샷 2019-03-29 오전 10 31 48 1" src="https://user-images.githubusercontent.com/39326928/55203230-12cdae80-520e-11e9-8df1-3040539cd37a.png">

- 보존·복원 -> 기록 보존·복원
- 교육 프로그램 -> 교육 및 프로그램
