### ISSUE TITLE
시리즈 화면 넘어가는 시간 로딩 지연 

### ISSUE THREAD

**Issue by daamable** [seoul-metropolitan-archives/sdaweb#94]

**Comment by woonjjang** [comment]
실서버를 확인해 본다. 
이유 - 처음 선택한 분류자에 포함되어 있는 시리즈 목록에서 다음 시리즈 세부 항목으로 넘길 때 계산식이 많이 들어가 있는 상황으로 이해

**Comment by mozodev** [comment]
서울특별시 기록 
http://52.79.195.15/browse-class/OC-0003
공직자선거 관련 서울시 사진기록 1960 ~ 1988 (캐시 전에는 상당히 느린 화면)
http://52.79.195.15/browse-class/OC-0003/4179 (캐시 완료 후 빨라짐)
