### ISSUE TITLE
분류 아이콘 수정 

### ISSUE THREAD

**Issue by daamable** [seoul-metropolitan-archives/sdaweb#95]
![스크린샷 2019-03-15 오후 7 28 23](https://user-images.githubusercontent.com/39326928/54425391-8d9bc180-4758-11e9-857b-58966321cc71.png)

- Subject -> 주제 
- Organization -> -> 출처 
- Collection -> 컬렉션

**Comment by daamable** [comment]
![스크린샷 2019-03-15 오후 7 31 35](https://user-images.githubusercontent.com/39326928/54425560-f6833980-4758-11e9-974b-a9eb159ec1a7.png)


분류 최하위 분류자만 보여야 함. 즉 서울특별시 기록만 보여야 함.

**Comment by daamable** [comment]
![스크린샷 2019-03-15 오후 7 35 04](https://user-images.githubusercontent.com/39326928/54425752-77dacc00-4759-11e9-9b10-84a7e6693706.png)


- 위에서 첫 번째 점선을 실선으로

**Comment by woonjjang** [comment]
영어분류자를 한글 분류자로 바꾼다.
디자인 되어 있는 것은 용님이 전달함.

**Comment by mozodev** [comment]
완료

**Comment by daamable** [comment]
[천천히 반영해주셔도 됩니다] 
분류 보여지는 화면에서 순서 교체 : 주제 - 컬렉션 - 출처
