### ISSUE TITLE
[Easy] [주요 추진경과] 워딩 수정 

### ISSUE THREAD

**Issue by daamable** [seoul-metropolitan-archives/sdaweb#97]
<img width="411" alt="스크린샷 2019-03-15 오후 8 35 45" src="https://user-images.githubusercontent.com/39326928/54428806-f76c9900-4761-11e9-955c-293596eb4ec5.png">

주요 추진경과에서 '주요' 를 뺀다

**Comment by daamable** [comment]
<img width="1163" alt="스크린샷 2019-03-15 오후 8 36 21" src="https://user-images.githubusercontent.com/39326928/54428825-06ebe200-4762-11e9-9e09-4b4f57355775.png">


서울기록원 건립 timelapse 워딩 삭제

**Comment by woonjjang** [comment]
수정했습니다. (03.17)

**Comment by daamable** [comment]
> 수정했습니다. (03.17)

한번 더 확인 부탁드립니다.

**Comment by daamable** [comment]
확인하였고 이슈를 닫습니다.

**Comment by daamable** [comment]
<img width="831" alt="스크린샷 2019-03-19 오전 10 57 18" src="https://user-images.githubusercontent.com/39326928/54602759-dff51f00-4a85-11e9-9382-295dc0645b66.png">

**Comment by daamable** [comment]
타임랩스 밑에 줄은 다시 살린다(제가 이따가 다시 제대로 쓸게요)

**Comment by daamable** [comment]
<img width="1163" alt="54428825-06ebe200-4762-11e9-9e09-4b4f57355775-2" src="https://user-images.githubusercontent.com/39326928/54651000-2da87080-4af4-11e9-940d-d3bd0ea3c7e8.png">

영상 아래 모든 문장을 삭제해 주셨는데요. '서울기록원 건립 Timelapse' 이 문장은 삭제가 맞구요. 
아래의 문장은 넣어주시면 좋겠습니다. 

--
서울기록원 건축 과정(2016-2018)을 촬영한 타임랩스 영상입니다. 건축 공정의 개별 사진(135장)은 서울기록원 공식 페이스북 계정의 <건축공사> 사진첩에서 확인하실 수 있습니다.

**Comment by css3studio** [comment]
'서울기록원 건립 Timelapse' 을 삭제하고, 링크문구에 밑줄 추가하였습니다.
