### ISSUE TITLE
[연구보고서] 아이콘 이미지 사이즈 

### ISSUE THREAD

**Issue by daamable** [seoul-metropolitan-archives/sdaweb#98]
<img width="446" alt="스크린샷 2019-03-15 오후 8 37 19" src="https://user-images.githubusercontent.com/39326928/54428857-284cce00-4762-11e9-908c-d6b328e0d249.png">

연구보고서 아이콘 이미지 회색박스보다 작은 것으로 모두 맞추기

**Comment by daamable** [comment]
Safari에서는 정상적으로 보이는데 Chrome에서는 일부 오류입니다. 
Safari 이외 Chrome, IE 등 다른 브라우저에서도 오류가 나는지 확인이 필요한 상황입니다. 

@css3studio

**Comment by css3studio** [comment]
수정하였습니다
http://52.79.195.15/posts/report

**Comment by daamable** [comment]
사파리, 크롬, IE 확인했고 이슈를 닫습니다.
